/* 09.19 수정 
 그냥 전체 복사 붙여넣기 하면 됨

	=====참고사항 =======

피자 사진명 - 불고기.jpg , 불고기D.jpg,  불고기H.png 
           이런 형식으로 메뉴명.확장자   ** 파일명에 공백 없도록 해야됨  

 주소 나눌 때   상세주소와 기본주소 사이에 %&@#*^$@! 넣기


디렉토리 구조
 ㄴ-  큰 디렉토리만 지키기 ( view - WEB-INF 밑에 )
			

지점명에 '도미노피자' 뺄 것 , 상세주소에는 포함

'||chr(38)||' 
  and(&) 자리에 들어갈것


 erm에서 출력한 ddl문 오라클에 입력 할 때 
  ALTER TABLE 부분 밑에부분으로 덮어쓸 것 


********* SOTRES 에 X,Y 좌표 컬럼추가됨   9/12
 s_topping 실험쿼리 추가

*/




/* 자식키 있어도 삭제하기 - 
 Create Foreign Keys  ~ references 끝까지 덮어쓰기
   자식키가 참조하고 있어도 삭제 할 수 있도록 설정해줌 */
	


/*
ALTER TABLE BUY_COUPON DROP FOREIGN KEY(ID);


ALTER TABLE BUY_COUPON
	ADD FOREIGN KEY (ID)
	REFERENCES CUSTOMER (ID) ON DELETE CASCADE
;


ALTER TABLE CR_JOIN
	ADD FOREIGN KEY (ID)
	REFERENCES CUSTOMER (ID) ON DELETE CASCADE
;


ALTER TABLE DELADDR
	ADD FOREIGN KEY (ID)
	REFERENCES CUSTOMER (ID) ON DELETE CASCADE
;


ALTER TABLE MY_CUPON
	ADD FOREIGN KEY (ID)
	REFERENCES CUSTOMER (ID) ON DELETE CASCADE
;


ALTER TABLE SALES
	ADD FOREIGN KEY (ID)
	REFERENCES CUSTOMER (ID) ON DELETE CASCADE
;


ALTER TABLE USE_GIFT
	ADD FOREIGN KEY (ID)
	REFERENCES CUSTOMER (ID) ON DELETE CASCADE
;


ALTER TABLE PIZZA_DOUGH
	ADD FOREIGN KEY (DOUGH_NO)
	REFERENCES DOUGH (DOUGH_NO) ON DELETE CASCADE
;


ALTER TABLE GIFTCONE_C
	ADD FOREIGN KEY (COUPON_NO)
	REFERENCES GIFTCONE (COUPON_NO) ON DELETE CASCADE
	
;


ALTER TABLE BUY_COUPON
	ADD FOREIGN KEY (G_CODE)
	REFERENCES GIFTCONE_C (G_CODE) ON DELETE CASCADE
;


ALTER TABLE GIFT_DATE
	ADD FOREIGN KEY (G_CODE)
	REFERENCES GIFTCONE_C (G_CODE) ON DELETE CASCADE
;


ALTER TABLE USE_GIFT
	ADD FOREIGN KEY (G_CODE)
	REFERENCES GIFTCONE_C (G_CODE) ON DELETE CASCADE
;


ALTER TABLE USE_SAILCUPPON
	ADD FOREIGN KEY (MC_NO)
	REFERENCES MY_CUPON (MC_NO) ON DELETE CASCADE
;


ALTER TABLE PIZZA_DOUGH
	ADD FOREIGN KEY (P_NO)
	REFERENCES PIZZA (P_NO) ON DELETE CASCADE
;


ALTER TABLE GIFTCONE
	ADD FOREIGN KEY (D_NO)
	REFERENCES PIZZA_DOUGH (D_NO) ON DELETE CASCADE
;


ALTER TABLE P_NUTRIENT
	ADD FOREIGN KEY (D_NO)
	REFERENCES PIZZA_DOUGH (D_NO) ON DELETE CASCADE
;


ALTER TABLE CR_JOIN
	ADD FOREIGN KEY (R_NO)
	REFERENCES RATING (R_NO) ON DELETE CASCADE
;


ALTER TABLE RATING_CUPPON
	ADD FOREIGN KEY (R_NO)
	REFERENCES RATING (R_NO) ON DELETE CASCADE
;


ALTER TABLE MY_CUPON
	ADD FOREIGN KEY (C_NO)
	REFERENCES SAILE_COUPON (C_NO) ON DELETE CASCADE
;


ALTER TABLE RATING_CUPPON
	ADD FOREIGN KEY (C_NO)
	REFERENCES SAILE_COUPON (C_NO) ON DELETE CASCADE
;


ALTER TABLE SALES_MENU
	ADD FOREIGN KEY (SA_NO)
	REFERENCES SALES (SA_NO) ON DELETE CASCADE
;


ALTER TABLE WHETHER
	ADD FOREIGN KEY (SA_NO)
	REFERENCES SALES (SA_NO) ON DELETE CASCADE
;


ALTER TABLE S_TOPPING
	ADD FOREIGN KEY (SM_NO)
	REFERENCES SALES_MENU (SM_NO) ON DELETE CASCADE
;


ALTER TABLE S_NUTRIENT
	ADD FOREIGN KEY (S_NO)
	REFERENCES SIDE (S_NO) ON DELETE CASCADE
;


ALTER TABLE DELADDR
	ADD FOREIGN KEY (ST_NO)
	REFERENCES STORES (ST_NO) ON DELETE CASCADE
;


ALTER TABLE SALES
	ADD FOREIGN KEY (ST_NO)
	REFERENCES STORES (ST_NO) ON DELETE CASCADE
;


ALTER TABLE USE_GIFT
	ADD FOREIGN KEY (ST_NO)
	REFERENCES STORES (ST_NO) ON DELETE CASCADE
;


ALTER TABLE TOPPING_SIZE
	ADD FOREIGN KEY (T_CODE)
	REFERENCES TOPPING (T_CODE) ON DELETE CASCADE
; 


ALTER TABLE S_TOPPING
	ADD FOREIGN KEY (TS_NO)
	REFERENCES TOPPING_SIZE (TS_NO) ON DELETE CASCADE
;


ALTER TABLE T_NUTRIENT
	ADD FOREIGN KEY (TS_NO)
	REFERENCES TOPPING_SIZE (TS_NO) ON DELETE CASCADE
;

*/



/* -- CMD 가독성향상
SET LINESIZE2000;
COL P_name FOR A10
COL POST FOR A8
COL EMAIL FOR A8
COL ID FOR A8
COL PASS FOR A8
COL NAME FOR A8
COL BIRTH FOR A8
COL TEL FOR A8

COL SA_ADDR FOR A15
COL SA_PRO FOR A15
*/





/*

DROP SEQUENCE SEQ_MY_CUPON_MC_NO;
DROP SEQUENCE SEQ_PIZZA_P_NO;
DROP SEQUENCE SEQ_DOUGH_DOUGH_NO;
DROP SEQUence SEQ_PIZZA_DOUGH_D_NO;
DROP SEQUENCE SEQ_P_NUTRIENT_N_NO;
DROP SEQUENCE SEQ_SIDE_S_NO;
DROP SEQUENCE  SEQ_SALES_SA_NO;
DROP SEQUENCE  SEQ_STORES_ST_NO;
DROP SEQUENCE SEQ_TOPPING_SIZE_TS_NO;
DROP SEQUENCE SEQ_TOPPING_T_CODE;
DROP SEQUENCE  SEQ_SAUCE_SC_NO;
DROP SEQUENCE SEQ_PICKLE_PC_NO;
DROP SEQUENCE SEQ_DRINK_DR_NO;
DROP SEQUENCE SEQ_RATING_R_NO;
DROP SEQUENCE SEQ_RATING_CUPPON_RC_NO;
DROP SEQUENCE  SEQ_EVENT_E_NO;
DROP SEQUENCE  SEQ_NOTICE_N_NO;
DROP SEQUENCE  SEQ_SAILE_COUPON_C_NO;
DROP SEQUENCE  SEQ_MC_COUPON_MC_NO;
DROP SEQUENCE SEQ_SALES_MENU_SM_NO;
DROP SEQUENCE SEQ_DELADDR_DE_NO;
DROP SEQUENCE SEQ_PIZZA_SAUCE_PS_NO;

CREATE SEQUENCE SEQ_PIZZA_SAUCE_PS_NO START WITH 0 MINVALUE -99  NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_DOUGH_DOUGH_NO START WITH 5 MINVALUE -99  NOCACHE NOCYCLE;
create sequence SEQ_PIZZA_DOUGH_D_NO START WITH 0 MINVALUE -99  NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_P_NUTRIENT_N_NO START WITH 0 MINVALUE -99  NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_SIDE_S_NO    START WITH 0 MINVALUE -99  NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_PIZZA_P_NO START WITH 2 MINVALUE -99  NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_SALES_SA_NO   START WITH 0 MINVALUE -99  NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_STORES_ST_NO   START WITH 0 MINVALUE -99  NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_TOPPING_SIZE_TS_NO START WITH 0 MINVALUE -99  NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_TOPPING_T_CODE START WITH 0 MINVALUE -99  NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_SAUCE_SC_NO   START WITH 0 MINVALUE -99  NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_PICKLE_PC_NO    START WITH 0 MINVALUE -99  NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_DRINK_DR_NO  START WITH 0 MINVALUE -99  NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_RATING_R_NO    START WITH 0 MINVALUE -99  NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_RATING_CUPPON_RC_NO    START WITH 0 MINVALUE -99  NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_EVENT_E_NO   START WITH 0 MINVALUE -99  NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_NOTICE_N_NO   START WITH 0 MINVALUE -99  NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_SAILE_COUPON_C_NO   START WITH 0 MINVALUE -99  NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_MC_COUPON_MC_NO   START WITH 0 MINVALUE -99  NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_SALES_MENU_SM_NO START WITH 0 MINVALUE -99  NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_DELADDR_DE_NO  START WITH 0 MINVALUE -99  NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_MY_CUPON_MC_NO  START WITH 0 MINVALUE -99  NOCACHE NOCYCLE;

*/




/* 휴지통 비우기 */

PURGE RECYCLEBIN;








INSERT INTO DOUGH VALUES(1,'오리지널',0);
INSERT INTO DOUGH VALUES(2,'나폴리',0);
INSERT INTO DOUGH VALUES(3,'씬',0);
INSERT INTO DOUGH VALUES(4,'곡물도우',2000);


INSERT INTO PAY VALUES(
SEQ_PAY_PAY_NO.NEXTVAL,
1,
'신용카드 결제'
);
INSERT INTO PAY VALUES(
SEQ_PAY_PAY_NO.NEXTVAL,
1,
'모바일 결제'
);

INSERT INTO PAY VALUES(
SEQ_PAY_PAY_NO.NEXTVAL,
2,
'현금 결제'
);
INSERT INTO PAY VALUES(
SEQ_PAY_PAY_NO.NEXTVAL,
2,
'신용카드 결제'
);



INSERT INTO PIZZA VALUES(
0,
'마이키친 기본피자',
'마이키친',
null,
14000,
19000,
null,
'마이키친.jpg',
null,
null,
null);

INSERT INTO PIZZA_DOUGH VALUES(SEQ_PIZZA_DOUGH_D_NO.NEXTVAL,0,1); 
INSERT INTO P_NUTRIENT VALUES(SEQ_P_NUTRIENT_N_NO.NEXTVAL,SEQ_PIZZA_DOUGH_D_NO.CURRVAL,'L','784','1조각','98','253','10','4','469','4');
INSERT INTO P_NUTRIENT VALUES(SEQ_P_NUTRIENT_N_NO.NEXTVAL,SEQ_PIZZA_DOUGH_D_NO.CURRVAL,'M','443','1조각','55','151','6','3','258','2');


INSERT INTO PIZZA_DOUGH VALUES(SEQ_PIZZA_DOUGH_D_NO.NEXTVAL,0,2); 
INSERT INTO P_NUTRIENT VALUES(SEQ_P_NUTRIENT_N_NO.NEXTVAL,SEQ_PIZZA_DOUGH_D_NO.CURRVAL,'L','575','1조각','72','186','4','4','415','3');
INSERT INTO P_NUTRIENT VALUES(SEQ_P_NUTRIENT_N_NO.NEXTVAL,SEQ_PIZZA_DOUGH_D_NO.CURRVAL,'M','321','1조각','40','107','4','2','219','2');

INSERT INTO PIZZA_DOUGH VALUES(SEQ_PIZZA_DOUGH_D_NO.NEXTVAL,0,3); 
INSERT INTO P_NUTRIENT VALUES(SEQ_P_NUTRIENT_N_NO.NEXTVAL,SEQ_PIZZA_DOUGH_D_NO.CURRVAL,'L','453','1조각','57','157','8','5','360','2');
INSERT INTO P_NUTRIENT VALUES(SEQ_P_NUTRIENT_N_NO.NEXTVAL,SEQ_PIZZA_DOUGH_D_NO.CURRVAL,'M','251','1조각','31','88','2','3','208','1');

INSERT INTO PIZZA_DOUGH VALUES(SEQ_PIZZA_DOUGH_D_NO.NEXTVAL,0,4); 
INSERT INTO P_NUTRIENT VALUES(SEQ_P_NUTRIENT_N_NO.NEXTVAL,SEQ_PIZZA_DOUGH_D_NO.CURRVAL,'L','950','1조각','119','319','17','8','584','2');
INSERT INTO P_NUTRIENT VALUES(SEQ_P_NUTRIENT_N_NO.NEXTVAL,SEQ_PIZZA_DOUGH_D_NO.CURRVAL,'M','581','1조각','73','199','9','4','333','1');


INSERT INTO PIZZA VALUES(
1,
'하프앤하프 피자',
'하프앤하프',
null,
0,
0,
null,
'하프앤하프.jpg',
null,
null,
null);

INSERT INTO PIZZA_DOUGH VALUES(SEQ_PIZZA_DOUGH_D_NO.NEXTVAL,1,1);
INSERT INTO PIZZA_DOUGH VALUES(SEQ_PIZZA_DOUGH_D_NO.NEXTVAL,1,2);
INSERT INTO PIZZA_DOUGH VALUES(SEQ_PIZZA_DOUGH_D_NO.NEXTVAL,1,3);
INSERT INTO PIZZA_DOUGH VALUES(SEQ_PIZZA_DOUGH_D_NO.NEXTVAL,1,4);


INSERT INTO PIZZA VALUES(SEQ_PIZZA_P_NO.NEXTVAL,'직화 스테이크','프리미엄',
'직화 스테이크, 케이준새우, 치즈 4종(프로볼로네, 보코치니, 파르메산 치즈, 모차렐라), 양송이, 베이컨칩, 적양파, 청피망, 구운감자, 파슬리, 선드라이토마토, 토마토 소스, 갈릭올리브 소스 *베이컨칩 일시적으로 와규크럼블로 대체 → 상세내용은 도미노뉴스를 확인 하시기 바랍니다.',
27500,32900,
'직화 스테이크(쇠고기): 호주산 / 베이컨칩(돼지고기): 미국산, 스페인산, 아일랜드산 / 모차렐라치즈: 미국산 / 오리지널, 나폴리 도우: 미국산, 캐나다산 / 씬 도우: 미국산 *베이컨칩 일시적으로 와규크럼블로 대체 → 상세내용은 도미노뉴스를 확인 하시기 바랍니다.',
'직화스테이크.jpg','직화스테이크H.png','직화스테이크D.jpg',
'불에 직접 구워 불 맛 특유의 그윽한 향과 맛이 가득한 직화 스테이크와 탱글탱글한 통새우, 4가지 이탈리안 치즈의 역대급 콜라보!<BR/>
*베이컨칩 일시적으로 와규크럼블로 대체 → 상세내용은 도미노뉴스를 확인 하시기 바랍니다.'
);




INSERT INTO PIZZA_DOUGH VALUES(SEQ_PIZZA_DOUGH_D_NO.NEXTVAL,SEQ_PIZZA_P_NO.CURRVAL,1);
INSERT INTO P_NUTRIENT VALUES(SEQ_P_NUTRIENT_N_NO.NEXTVAL,SEQ_PIZZA_DOUGH_D_NO.CURRVAL,'L','989','1조각','124','302','15','5','404','4');
INSERT INTO P_NUTRIENT VALUES(SEQ_P_NUTRIENT_N_NO.NEXTVAL,SEQ_PIZZA_DOUGH_D_NO.CURRVAL,'M',653,'2조각',	163,	398,	20,	8,	563,	5);



INSERT INTO PIZZA_DOUGH VALUES(SEQ_PIZZA_DOUGH_D_NO.NEXTVAL,SEQ_PIZZA_P_NO.CURRVAL,2);
INSERT INTO P_NUTRIENT VALUES(SEQ_P_NUTRIENT_N_NO.NEXTVAL,SEQ_PIZZA_DOUGH_D_NO.CURRVAL,'L',789,'2조각',	197,	477,	25,	9,	769,	8
);
INSERT INTO P_NUTRIENT VALUES(SEQ_P_NUTRIENT_N_NO.NEXTVAL,SEQ_PIZZA_DOUGH_D_NO.CURRVAL,'M',542,'2조각'	,136,	322,	17,	7,	404,	5
);

INSERT INTO PIZZA_DOUGH VALUES(SEQ_PIZZA_DOUGH_D_NO.NEXTVAL,SEQ_PIZZA_P_NO.CURRVAL,3);
INSERT INTO P_NUTRIENT VALUES(SEQ_P_NUTRIENT_N_NO.NEXTVAL,SEQ_PIZZA_DOUGH_D_NO.CURRVAL,'L',655,'2조각',164,	427,	22,	10,	663,	7
);
INSERT INTO P_NUTRIENT VALUES(SEQ_P_NUTRIENT_N_NO.NEXTVAL,SEQ_PIZZA_DOUGH_D_NO.CURRVAL,'M',467,'2조각',	117	,287,	15,	8,	490,	5



/*  곡물 도우 */
INSERT INTO PIZZA_DOUGH VALUES(SEQ_PIZZA_DOUGH_D_NO.NEXTVAL,SEQ_PIZZA_P_NO.CURRVAL,4); 
INSERT INTO P_NUTRIENT VALUES(SEQ_P_NUTRIENT_N_NO.NEXTVAL,SEQ_PIZZA_DOUGH_D_NO.CURRVAL,'L',997,'1조각',	125,	307,	15,	4,	421,	5
);
INSERT INTO P_NUTRIENT VALUES(SEQ_P_NUTRIENT_N_NO.NEXTVAL,SEQ_PIZZA_DOUGH_D_NO.CURRVAL,'M',655,'2조각',	164,	414,	18,	7	,522,	8
);



INSERT INTO PIZZA VALUES(SEQ_PIZZA_P_NO.NEXTVAL,'킹프론 씨푸드','프리미엄',
'킹프론, 칼라마리, 페타크림치즈, 만체고 슈레드치즈, 파르메산치즈, 모차렐라치즈, 체더치즈, 새송이 버섯, 구운감자, 양송이, 청피망, 적양파, 파슬리, 토마토소스',
28500,33900,
'모차렐라 치즈: 미국산 / 체더치즈: 뉴질랜드 산 / 칼라마리(오징어) : 칠레산 / 오리지널, 나폴리 도우: 미국산, 캐나다산 / 씬도우: 미국산',
'킹프론씨푸드.jpg','킹프론씨푸드H.png','킹프론씨푸드D.jpg',
'호스래디시 소스가 더해져 고소한 풍미가 가득한 킹프론과 크레올 소스로 양념한 촉촉하고 부드러운 칼라마리, 깊은 풍미를 더해줄 5가지 치즈가 만난 화려한 씨푸드 만찬<br/>
* 본 제품에 포함되는 킹프론(새우)의 꼬리 부분이 다소 딱딱할 수 있으니, 어린이나 치아가 약하신 분들은 특히 취식 시 주의하시기 바랍니다.<br/>
* 만체고 슈레드 치즈(흰색)는 재료 본연의 맛을 살리기 위해 애프터쿠킹으로 토핑됩니다.<br/>
(완전히 녹지 않은 상태로 제공) 조리없이 드실 수 있는 치즈로 안심하고 드셔도 좋습니다.'
);


 
 
 
 

INSERT INTO PIZZA_DOUGH VALUES(SEQ_PIZZA_DOUGH_D_NO.NEXTVAL,SEQ_PIZZA_P_NO.CURRVAL,1);
INSERT INTO P_NUTRIENT VALUES(SEQ_P_NUTRIENT_N_NO.NEXTVAL,SEQ_PIZZA_DOUGH_D_NO.CURRVAL,'L',1103,'1조각',	138,	324,	14,	5,	518,	6
);
INSERT INTO P_NUTRIENT VALUES(SEQ_P_NUTRIENT_N_NO.NEXTVAL,SEQ_PIZZA_DOUGH_D_NO.CURRVAL,'M',653,'2조각',	109,	257,	13,	5,	419	,4
);



INSERT INTO PIZZA_DOUGH VALUES(SEQ_PIZZA_DOUGH_D_NO.NEXTVAL,SEQ_PIZZA_P_NO.CURRVAL,2);
INSERT INTO P_NUTRIENT VALUES(SEQ_P_NUTRIENT_N_NO.NEXTVAL,SEQ_PIZZA_DOUGH_D_NO.CURRVAL,'L',903,
'1조각',113,	245,	13,	5,	462,	4
);
INSERT INTO P_NUTRIENT VALUES(SEQ_P_NUTRIENT_N_NO.NEXTVAL,SEQ_PIZZA_DOUGH_D_NO.CURRVAL,'M',534,
'2조각',178,	404,	21,	8,	728,	7
);



INSERT INTO PIZZA_DOUGH VALUES(SEQ_PIZZA_DOUGH_D_NO.NEXTVAL,SEQ_PIZZA_P_NO.CURRVAL,3);
INSERT INTO P_NUTRIENT VALUES(SEQ_P_NUTRIENT_N_NO.NEXTVAL,SEQ_PIZZA_DOUGH_D_NO.CURRVAL,'L',767,
'2조각',192,	430,	23,	11,	803	,10
);
INSERT INTO P_NUTRIENT VALUES(SEQ_P_NUTRIENT_N_NO.NEXTVAL,SEQ_PIZZA_DOUGH_D_NO.CURRVAL,'M',462,
'2조각',154,	345	,19,	9,	681,	7
);



/*  곡물 도우 */
INSERT INTO PIZZA_DOUGH VALUES(SEQ_PIZZA_DOUGH_D_NO.NEXTVAL,SEQ_PIZZA_P_NO.CURRVAL,4); 
INSERT INTO P_NUTRIENT VALUES(SEQ_P_NUTRIENT_N_NO.NEXTVAL,SEQ_PIZZA_DOUGH_D_NO.CURRVAL,'L',1104,
'1조각',138,	302,	15,	5,	556,	7
);
INSERT INTO P_NUTRIENT VALUES(SEQ_P_NUTRIENT_N_NO.NEXTVAL,SEQ_PIZZA_DOUGH_D_NO.CURRVAL,'M',663,
'1조각',111,	253,	12,	4,	413,	5
);


INSERT INTO PIZZA VALUES(SEQ_PIZZA_P_NO.NEXTVAL,'와규 앤 비스테카','프리미엄',
'비스테카, 와규 크럼블, 로마노크림치즈, 프로볼로네 치즈, 보코치니 치즈, 파르메산 치즈, 모차렐라, 스모크 새송이 버섯, 아라비아타 소스',
27500,32900,
'비스테카(쇠고기): 호주산 / 와규 크럼블(쇠고기): 호주산 / 모차렐라 치즈: 미국산 / 오리지널, 나폴리 도우: 미국산, 캐나다산 / 씬도우: 미국',
'와규앤비스테카.jpg','와규앤비스테카H.png','와규앤비스테카D.jpg',
'소고기를 얇게 저며 구워먹는 이탈리안 요리 비스테카와 호주산 와규 크럼블, 5가지 프리미엄 치즈가 어우러져 깊고 풍부한 맛을 즐길 수 있는 피자'
);

 
 


INSERT INTO PIZZA_DOUGH VALUES(SEQ_PIZZA_DOUGH_D_NO.NEXTVAL,SEQ_PIZZA_P_NO.CURRVAL,1);
INSERT INTO P_NUTRIENT VALUES(SEQ_P_NUTRIENT_N_NO.NEXTVAL,SEQ_PIZZA_DOUGH_D_NO.CURRVAL,'L',
1043,'1조각',130,	305,	14,	5,	374,	8
);
INSERT INTO P_NUTRIENT VALUES(SEQ_P_NUTRIENT_N_NO.NEXTVAL,SEQ_PIZZA_DOUGH_D_NO.CURRVAL,'M',
615,'2조각',	154,	377	,16,	6	,387	,7
);



INSERT INTO PIZZA_DOUGH VALUES(SEQ_PIZZA_DOUGH_D_NO.NEXTVAL,SEQ_PIZZA_P_NO.CURRVAL,2);
INSERT INTO P_NUTRIENT VALUES(SEQ_P_NUTRIENT_N_NO.NEXTVAL,SEQ_PIZZA_DOUGH_D_NO.CURRVAL,'L',
855,'1조각',	107	,247,	16,	5,	310,	7
);
INSERT INTO P_NUTRIENT VALUES(SEQ_P_NUTRIENT_N_NO.NEXTVAL,SEQ_PIZZA_DOUGH_D_NO.CURRVAL,'M',
518,'2조각',	130,	306,	18,	6,	379	,7
);



INSERT INTO PIZZA_DOUGH VALUES(SEQ_PIZZA_DOUGH_D_NO.NEXTVAL,SEQ_PIZZA_P_NO.CURRVAL,3);
INSERT INTO P_NUTRIENT VALUES(SEQ_P_NUTRIENT_N_NO.NEXTVAL,SEQ_PIZZA_DOUGH_D_NO.CURRVAL,'L',
715,'2조각',	179,	477,	23,	12,	602	,15
);
INSERT INTO P_NUTRIENT VALUES(SEQ_P_NUTRIENT_N_NO.NEXTVAL,SEQ_PIZZA_DOUGH_D_NO.CURRVAL,'M',
414,'2조각',	104,	262,	12,	7,	307,	7
);




/*  곡물 도우 */
INSERT INTO PIZZA_DOUGH VALUES(SEQ_PIZZA_DOUGH_D_NO.NEXTVAL,SEQ_PIZZA_P_NO.CURRVAL,4); 
INSERT INTO P_NUTRIENT VALUES(SEQ_P_NUTRIENT_N_NO.NEXTVAL,SEQ_PIZZA_DOUGH_D_NO.CURRVAL,'L',
1051,'1조각',	131,	306,	13,	6,	363,	8
);
INSERT INTO P_NUTRIENT VALUES(SEQ_P_NUTRIENT_N_NO.NEXTVAL,SEQ_PIZZA_DOUGH_D_NO.CURRVAL,'M',
623,'2조각	',156	,354	,16,	6,	399,	9
);






INSERT INTO PIZZA VALUES(SEQ_PIZZA_P_NO.NEXTVAL,'브레이즈드 포크','프리미엄',
'브레이즈드 포크, 생 모차렐라 치즈 슬라이스, 그뤼에르멜팅치즈, 브리 치즈 소스, 페터 크림 치즈, 모차렐라 치즈, 아라비아타 소스, 양파, 선 드라이 토마토, 파슬리',
27500,32900,
'오리지널, 나폴리 도우: 미국산, 캐나다산 / 씬도우: 미국산 / 브레이즈드 포크(돼지고기): 미국산 / 모차렐라 치즈: 미국산 / 와규(쇠고기) : 호주산',
'브레이즈드포크.jpg','브레이즈드포크H.png','브레이즈드포크D.jpg',
'육즙 가득, 풍미 가득한 브레이즈드 포크와 진한 그뤼에르멜팅치즈, 쫄깃한 생 모차렐라 치즈 등 5가지 치즈의 풍부한 맛을 느낄 수 있는 피자'
);

 
 


INSERT INTO PIZZA_DOUGH VALUES(SEQ_PIZZA_DOUGH_D_NO.NEXTVAL,SEQ_PIZZA_P_NO.CURRVAL,1);
INSERT INTO P_NUTRIENT VALUES(SEQ_P_NUTRIENT_N_NO.NEXTVAL,SEQ_PIZZA_DOUGH_D_NO.CURRVAL,'L',
1024,'1조각',	128,	351,	17,	8	,479,	5
);
INSERT INTO P_NUTRIENT VALUES(SEQ_P_NUTRIENT_N_NO.NEXTVAL,SEQ_PIZZA_DOUGH_D_NO.CURRVAL,'M',
605,'2조각',	151,	206,	20	,10,	531,	6
);


INSERT INTO PIZZA_DOUGH VALUES(SEQ_PIZZA_DOUGH_D_NO.NEXTVAL,SEQ_PIZZA_P_NO.CURRVAL,2);
INSERT INTO P_NUTRIENT VALUES(SEQ_P_NUTRIENT_N_NO.NEXTVAL,SEQ_PIZZA_DOUGH_D_NO.CURRVAL,'L',
813,'1조각',	102,	297,	15	,8,	418	,4
);

INSERT INTO P_NUTRIENT VALUES(SEQ_P_NUTRIENT_N_NO.NEXTVAL,SEQ_PIZZA_DOUGH_D_NO.CURRVAL,'M',
476,'2조각',	119	,350	,17	,10,	470	,5
);



INSERT INTO PIZZA_DOUGH VALUES(SEQ_PIZZA_DOUGH_D_NO.NEXTVAL,SEQ_PIZZA_P_NO.CURRVAL,3);
INSERT INTO P_NUTRIENT VALUES(SEQ_P_NUTRIENT_N_NO.NEXTVAL,SEQ_PIZZA_DOUGH_D_NO.CURRVAL,'L',
676,'2조각',	169,	531,	26,	18,	700	,7
);
INSERT INTO P_NUTRIENT VALUES(SEQ_P_NUTRIENT_N_NO.NEXTVAL,SEQ_PIZZA_DOUGH_D_NO.CURRVAL,'M',
400,'2조각',	100	,320,	18,	11,	402,	4
);




/*  곡물 도우 */
INSERT INTO PIZZA_DOUGH VALUES(SEQ_PIZZA_DOUGH_D_NO.NEXTVAL,SEQ_PIZZA_P_NO.CURRVAL,4); 
INSERT INTO P_NUTRIENT VALUES(SEQ_P_NUTRIENT_N_NO.NEXTVAL,SEQ_PIZZA_DOUGH_D_NO.CURRVAL,'L',
1017,'1조각',	127,	343,	16,	8,	447,	5
);
INSERT INTO P_NUTRIENT VALUES(SEQ_P_NUTRIENT_N_NO.NEXTVAL,SEQ_PIZZA_DOUGH_D_NO.CURRVAL,'M',
606,'2조각',	152,	423,	22,	9,	492	,7
);






INSERT INTO PIZZA VALUES(SEQ_PIZZA_P_NO.NEXTVAL,'꽃게 온더 피자','프리미엄',
'꽃게살, 킹프론, 칼라마리 큐브, 모차렐라, 구운감자, 양송이, 라클렛치즈 소스, 할라피뇨 호스래디시 소스, 호스래디시 소스 등',
28500,33900,
'칼라마리 큐브: 칠레 / 꽃게살: 인도네시아, 베트남',
'꽃게온더피자.jpg','꽃게온더피자H.png','꽃게온더피자D.jpg',
'꽃게살, 킹프론, 칼라마리 큐브까지 풍부한 씨푸드와 구운감자에 스위스 전통요리 "라클렛" 치즈 소스가 가미된 프리미엄 피자<br/>
*킹프론(새우) 꼬리 부분은 다소 딱딱 할 수 있으며, 꽃게살에 간혹 게껍데기가 포함되어 있을 수 있으니 취식 시 주의하시기 바랍니다.'
);




INSERT INTO PIZZA_DOUGH VALUES(SEQ_PIZZA_DOUGH_D_NO.NEXTVAL,SEQ_PIZZA_P_NO.CURRVAL,1);
INSERT INTO P_NUTRIENT VALUES(SEQ_P_NUTRIENT_N_NO.NEXTVAL,SEQ_PIZZA_DOUGH_D_NO.CURRVAL,'L',
959,'1조각',120,	267,	14,	2	,381,	4
);
INSERT INTO P_NUTRIENT VALUES(SEQ_P_NUTRIENT_N_NO.NEXTVAL,SEQ_PIZZA_DOUGH_D_NO.CURRVAL,'M',
573,'2조각',	191,	399	,21,	3,	621,	6
);



INSERT INTO PIZZA_DOUGH VALUES(SEQ_PIZZA_DOUGH_D_NO.NEXTVAL,SEQ_PIZZA_P_NO.CURRVAL,2);
INSERT INTO P_NUTRIENT VALUES(SEQ_P_NUTRIENT_N_NO.NEXTVAL,SEQ_PIZZA_DOUGH_D_NO.CURRVAL,'L',
778,'1조각',	97,	208	,11,	2,	347,	4
);
INSERT INTO P_NUTRIENT VALUES(SEQ_P_NUTRIENT_N_NO.NEXTVAL,SEQ_PIZZA_DOUGH_D_NO.CURRVAL,'M',
472,'2조각',	157,	332,	17	,4,	582,	6
);



INSERT INTO PIZZA_DOUGH VALUES(SEQ_PIZZA_DOUGH_D_NO.NEXTVAL,SEQ_PIZZA_P_NO.CURRVAL,3);
INSERT INTO P_NUTRIENT VALUES(SEQ_P_NUTRIENT_N_NO.NEXTVAL,SEQ_PIZZA_DOUGH_D_NO.CURRVAL,'L',
614,'1조각',	77,	177,	9,	3,	292,	3
);
INSERT INTO P_NUTRIENT VALUES(SEQ_P_NUTRIENT_N_NO.NEXTVAL,SEQ_PIZZA_DOUGH_D_NO.CURRVAL,'M',
350,'2조각',	117,	268,	14,	5,	462,	5
);



/*  곡물 도우 */
INSERT INTO PIZZA_DOUGH VALUES(SEQ_PIZZA_DOUGH_D_NO.NEXTVAL,SEQ_PIZZA_P_NO.CURRVAL,4); 
INSERT INTO P_NUTRIENT VALUES(SEQ_P_NUTRIENT_N_NO.NEXTVAL,SEQ_PIZZA_DOUGH_D_NO.CURRVAL,'L',
955,'1조각',	119	,271	,13	,2,	381,	6
);
INSERT INTO P_NUTRIENT VALUES(SEQ_P_NUTRIENT_N_NO.NEXTVAL,SEQ_PIZZA_DOUGH_D_NO.CURRVAL,'M',
585,'2조각',	195,	429,	22,	4	,638,	10
);






/* 클래식 피자 */


INSERT INTO PIZZA VALUES(
SEQ_PIZZA_P_NO.NEXTVAL,
'치즈',
'클래식',
'모차렐라 치즈',
14500,
20900,
'모차렐라 치즈: 미국산 / 오리지널, 나폴리 도우: 미국산, 캐나다산 / 씬 도우: 미국산',
'치즈.jpg',
'치즈H.png',
'치즈D.jpg',
'피자도우와 치즈만으로 승부수를 걸었다.<br/>
토마토 소스와 모차렐라 치즈를 가득 넣은 피자. 기본기에 충실한 도미노 피자를 느껴보자.'
);

 
 

INSERT INTO PIZZA_DOUGH VALUES(SEQ_PIZZA_DOUGH_D_NO.NEXTVAL,SEQ_PIZZA_P_NO.CURRVAL,1);
INSERT INTO P_NUTRIENT VALUES(SEQ_P_NUTRIENT_N_NO.NEXTVAL,SEQ_PIZZA_DOUGH_D_NO.CURRVAL,'L',
764,'2조각',	191,	466	,24,	6,	638,	7
);
INSERT INTO P_NUTRIENT VALUES(SEQ_P_NUTRIENT_N_NO.NEXTVAL,SEQ_PIZZA_DOUGH_D_NO.CURRVAL,'M',
447,'2조각',	112,	285,	15,	4	,403,	5
);

 
 

INSERT INTO PIZZA_DOUGH VALUES(SEQ_PIZZA_DOUGH_D_NO.NEXTVAL,SEQ_PIZZA_P_NO.CURRVAL,2);
INSERT INTO P_NUTRIENT VALUES(SEQ_P_NUTRIENT_N_NO.NEXTVAL,SEQ_PIZZA_DOUGH_D_NO.CURRVAL,'L',
544,'2조각',	136,	352,19,	7	,574,	6
);
INSERT INTO P_NUTRIENT VALUES(SEQ_P_NUTRIENT_N_NO.NEXTVAL,SEQ_PIZZA_DOUGH_D_NO.CURRVAL,'M',
308,'3조각',	116,	305,	18,	6,	460,	5
);

INSERT INTO PIZZA_DOUGH VALUES(SEQ_PIZZA_DOUGH_D_NO.NEXTVAL,SEQ_PIZZA_P_NO.CURRVAL,3);
INSERT INTO P_NUTRIENT VALUES(SEQ_P_NUTRIENT_N_NO.NEXTVAL,SEQ_PIZZA_DOUGH_D_NO.CURRVAL,'L',
441,'2조각',	110,	314,	17,	9,	423,	5
);
INSERT INTO P_NUTRIENT VALUES(SEQ_P_NUTRIENT_N_NO.NEXTVAL,SEQ_PIZZA_DOUGH_D_NO.CURRVAL,'M',
247,'4조각',	124,	374,	20,	11,	572,	5
);

INSERT INTO PIZZA_DOUGH VALUES(SEQ_PIZZA_DOUGH_D_NO.NEXTVAL,SEQ_PIZZA_P_NO.CURRVAL,4);
INSERT INTO P_NUTRIENT VALUES(SEQ_P_NUTRIENT_N_NO.NEXTVAL,SEQ_PIZZA_DOUGH_D_NO.CURRVAL,'L',
764,'2조각',	191,	491,	24,	7,	626,	11
);
INSERT INTO P_NUTRIENT VALUES(SEQ_P_NUTRIENT_N_NO.NEXTVAL,SEQ_PIZZA_DOUGH_D_NO.CURRVAL,'M',
448,'2조각',	112,	292,	14,	4	,345,	7
);




INSERT INTO PIZZA VALUES(
SEQ_PIZZA_P_NO.NEXTVAL,
'페퍼로니',
'클래식',
'모파렐라 치즈, 페퍼로니',
15500,
21900,
'페퍼로니: 돈육(국내산)+우유(호주산) / 모차렐라치즈: 미국산 / 오리지널, 나폴리 도우: 미국산, 캐나다산 / 씬 도우: 미국산',
'페퍼로니.jpg',
'페퍼로니H.png',
'페퍼로니D.jpg',
'진정한 피자매니아는 페퍼로니 피자만 고집한다.<br/>
산뜻한 토마토소스, 그 위에 페퍼로니와 주욱 늘어나는 모차렐라 치즈~<br/>
짭짤한 풍미가 일품인 정통 아메리칸 스타일'
);

 
 
 

INSERT INTO PIZZA_DOUGH VALUES(SEQ_PIZZA_DOUGH_D_NO.NEXTVAL,SEQ_PIZZA_P_NO.CURRVAL,1);
INSERT INTO P_NUTRIENT VALUES(SEQ_P_NUTRIENT_N_NO.NEXTVAL,SEQ_PIZZA_DOUGH_D_NO.CURRVAL,'L',
812,'1조각',	102,	271	,14,	5,	401	,4
);
INSERT INTO P_NUTRIENT VALUES(SEQ_P_NUTRIENT_N_NO.NEXTVAL,SEQ_PIZZA_DOUGH_D_NO.CURRVAL,'M',
470,'2조각',	118,	327,	16	,6	,445,	4
);

 


INSERT INTO PIZZA_DOUGH VALUES(SEQ_PIZZA_DOUGH_D_NO.NEXTVAL,SEQ_PIZZA_P_NO.CURRVAL,2);
INSERT INTO P_NUTRIENT VALUES(SEQ_P_NUTRIENT_N_NO.NEXTVAL,SEQ_PIZZA_DOUGH_D_NO.CURRVAL,'L',
590,'2조각',	148,	426,	24,	9,	680,	5
);
INSERT INTO P_NUTRIENT VALUES(SEQ_P_NUTRIENT_N_NO.NEXTVAL,SEQ_PIZZA_DOUGH_D_NO.CURRVAL,'M',
338,'2조각',	127,	384,	20,	8,	558,	4
);

INSERT INTO PIZZA_DOUGH VALUES(SEQ_PIZZA_DOUGH_D_NO.NEXTVAL,SEQ_PIZZA_P_NO.CURRVAL,3);
INSERT INTO P_NUTRIENT VALUES(SEQ_P_NUTRIENT_N_NO.NEXTVAL,SEQ_PIZZA_DOUGH_D_NO.CURRVAL,'L',
525,'2조각',	131,	386,	22,	11,	567,	4
);
INSERT INTO P_NUTRIENT VALUES(SEQ_P_NUTRIENT_N_NO.NEXTVAL,SEQ_PIZZA_DOUGH_D_NO.CURRVAL,'M',
291,'3조각',	109,	336	,18,	10,	503	,4
);

INSERT INTO PIZZA_DOUGH VALUES(SEQ_PIZZA_DOUGH_D_NO.NEXTVAL,SEQ_PIZZA_P_NO.CURRVAL,4);
INSERT INTO P_NUTRIENT VALUES(SEQ_P_NUTRIENT_N_NO.NEXTVAL,SEQ_PIZZA_DOUGH_D_NO.CURRVAL,'L',
839,'1조각',	105	,283	,14	,4	,348,	4
);
INSERT INTO P_NUTRIENT VALUES(SEQ_P_NUTRIENT_N_NO.NEXTVAL,SEQ_PIZZA_DOUGH_D_NO.CURRVAL,'M',
494,'2조각',	124,	341,	16,	6,	445,	6
);




INSERT INTO PIZZA VALUES(
SEQ_PIZZA_P_NO.NEXTVAL,
'불고기',
'클래식',
'모파렐라 치즈, 피망, 양파, 버섯, 불고기',
17500,
23900,
'불고기(쇠고기): 호주산 / 모차렐라치즈: 미국산 / 오리지널, 나폴리 도우: 미국산, 캐나다산 / 씬 도우: 미국산',
'불고기.jpg',
'불고기H.png',
'불고기D.jpg',
'한국의 대표음식 불고기와 피자가 만났다!<br/>
불고기양념의 달콤한 맛으로 어린 고객들의 입맛까지 사로잡은 가족메뉴'
);

 



INSERT INTO PIZZA_DOUGH VALUES(SEQ_PIZZA_DOUGH_D_NO.NEXTVAL,SEQ_PIZZA_P_NO.CURRVAL,1);
INSERT INTO P_NUTRIENT VALUES(SEQ_P_NUTRIENT_N_NO.NEXTVAL,SEQ_PIZZA_DOUGH_D_NO.CURRVAL,'L',
966,'1조각',	121,	291,	15,	5,	406,	6
);
INSERT INTO P_NUTRIENT VALUES(SEQ_P_NUTRIENT_N_NO.NEXTVAL,SEQ_PIZZA_DOUGH_D_NO.CURRVAL,'M',
516,'2조각',	129	,319,	16,	5,	441,	6
);


INSERT INTO PIZZA_DOUGH VALUES(SEQ_PIZZA_DOUGH_D_NO.NEXTVAL,SEQ_PIZZA_P_NO.CURRVAL,2);
INSERT INTO P_NUTRIENT VALUES(SEQ_P_NUTRIENT_N_NO.NEXTVAL,SEQ_PIZZA_DOUGH_D_NO.CURRVAL,'L',
707,'2조각',	177,	421,	2,	9,	696	,7
);
INSERT INTO P_NUTRIENT VALUES(SEQ_P_NUTRIENT_N_NO.NEXTVAL,SEQ_PIZZA_DOUGH_D_NO.CURRVAL,'M',
408,'2조각',	102,	250	,14,	5,	388,	4
);

INSERT INTO PIZZA_DOUGH VALUES(SEQ_PIZZA_DOUGH_D_NO.NEXTVAL,SEQ_PIZZA_P_NO.CURRVAL,3);
INSERT INTO P_NUTRIENT VALUES(SEQ_P_NUTRIENT_N_NO.NEXTVAL,SEQ_PIZZA_DOUGH_D_NO.CURRVAL,'L',
646,'2조각',	162,	394,	22,	10,	649,	8
);
INSERT INTO P_NUTRIENT VALUES(SEQ_P_NUTRIENT_N_NO.NEXTVAL,SEQ_PIZZA_DOUGH_D_NO.CURRVAL,'M',
334,'3조각',	125	,312,	18	,9,	545	,6
);

INSERT INTO PIZZA_DOUGH VALUES(SEQ_PIZZA_DOUGH_D_NO.NEXTVAL,SEQ_PIZZA_P_NO.CURRVAL,4);
INSERT INTO P_NUTRIENT VALUES(SEQ_P_NUTRIENT_N_NO.NEXTVAL,SEQ_PIZZA_DOUGH_D_NO.CURRVAL,'L',
966,'1조각',	121,	301	,15,	4	,400	,8
);
INSERT INTO P_NUTRIENT VALUES(SEQ_P_NUTRIENT_N_NO.NEXTVAL,SEQ_PIZZA_DOUGH_D_NO.CURRVAL,'M',
537,'2조각',134,	342,	16,	5	,458,	8
);



INSERT INTO PIZZA VALUES(
SEQ_PIZZA_P_NO.NEXTVAL,
'베이컨체더치즈',
'클래식',
'모차렐라 치즈, 체더치즈, 양파, 불고기, 베이컨',
18500,
24900,
'불고기(쇠고기): 호주산 / 베이컨(돼지고기): 미국산, 스페인산, 아일랜드산 / 체더치즈: 뉴질랜드산 / 모차렐라치즈: 미국산 / 오리지널, 나폴리 도우: 미국산, 캐나다산 / 씬 도우: 미국산',
'베이컨체더치즈.jpg',
'베이컨체더치즈H.png',
'베이컨체더치즈D.jpg',
'노오란 체더치즈의 고소함과 푸짐한 베이컨이 만들어내는 완벽한 콤비, 매니아층의 꾸준한 사랑을 받고 있는 도미노만의 메뉴'
);
INSERT INTO PIZZA_DOUGH VALUES(SEQ_PIZZA_DOUGH_D_NO.NEXTVAL,SEQ_PIZZA_P_NO.CURRVAL,1);
INSERT INTO P_NUTRIENT VALUES(SEQ_P_NUTRIENT_N_NO.NEXTVAL,SEQ_PIZZA_DOUGH_D_NO.CURRVAL,'L',
912,'1조각',	114,	311,	14,	6,	399,	4
);
INSERT INTO P_NUTRIENT VALUES(SEQ_P_NUTRIENT_N_NO.NEXTVAL,SEQ_PIZZA_DOUGH_D_NO.CURRVAL,'M',
516,'2조각',	129	,356,	18,	8,	529,	5
);

 
 
 
 
 

INSERT INTO PIZZA_DOUGH VALUES(SEQ_PIZZA_DOUGH_D_NO.NEXTVAL,SEQ_PIZZA_P_NO.CURRVAL,2);
INSERT INTO P_NUTRIENT VALUES(SEQ_P_NUTRIENT_N_NO.NEXTVAL,SEQ_PIZZA_DOUGH_D_NO.CURRVAL,'L',
705,'2조각',	176,	465,	24,	11	,696,	5
);
INSERT INTO P_NUTRIENT VALUES(SEQ_P_NUTRIENT_N_NO.NEXTVAL,SEQ_PIZZA_DOUGH_D_NO.CURRVAL,'M',
255,'3조각',	143,	382,	21,	9,	606,	5
);

INSERT INTO PIZZA_DOUGH VALUES(SEQ_PIZZA_DOUGH_D_NO.NEXTVAL,SEQ_PIZZA_P_NO.CURRVAL,3);
INSERT INTO P_NUTRIENT VALUES(SEQ_P_NUTRIENT_N_NO.NEXTVAL,SEQ_PIZZA_DOUGH_D_NO.CURRVAL,'L',
587,'2조각',	147,	437,	22,	14,	671,	4
);
INSERT INTO P_NUTRIENT VALUES(SEQ_P_NUTRIENT_N_NO.NEXTVAL,SEQ_PIZZA_DOUGH_D_NO.CURRVAL,'M',
334,'3조각',	125,	377,	19,	12,	525,	4
);

INSERT INTO PIZZA_DOUGH VALUES(SEQ_PIZZA_DOUGH_D_NO.NEXTVAL,SEQ_PIZZA_P_NO.CURRVAL,4);
INSERT INTO P_NUTRIENT VALUES(SEQ_P_NUTRIENT_N_NO.NEXTVAL,SEQ_PIZZA_DOUGH_D_NO.CURRVAL,'L',
903,'1조각',	113,	307,	14,	6,	455,	6
);
INSERT INTO P_NUTRIENT VALUES(SEQ_P_NUTRIENT_N_NO.NEXTVAL,SEQ_PIZZA_DOUGH_D_NO.CURRVAL,'M',
514,'2조각',	129,	355,	17,	7,	500,	7
);


INSERT INTO PIZZA VALUES(
SEQ_PIZZA_P_NO.NEXTVAL,
'슈퍼슈프림',
'클래식',
'모차렐라 치즈, 피망, 양파, 햄, 버섯, 옥수수, 불고기, 포크, 파인애플',
18500,
24900,
'불고기(쇠고기): 호주산 / 포크 토핑(돼지고기): 국내산 / 햄(돼지고기): 국내산 / 모차렐라 치즈: 미국산 / 오리지널, 나폴리 도우: 미국산, 캐나다산 / 씬 도우: 미국산',
'슈퍼슈프림.jpg',
'슈퍼슈프림H.png',
'슈퍼슈프림D.jpg',
'신선한 야채와 다양한 고기류를 토핑하여 맛만큼 알록달록 색감도 살아있는 피자.<br/>
스위트콘과 파인애플을 넣어 달콤한 맛이 가미된 도미노 특유의 맛'
);
 


INSERT INTO PIZZA_DOUGH VALUES(SEQ_PIZZA_DOUGH_D_NO.NEXTVAL,SEQ_PIZZA_P_NO.CURRVAL,1);
INSERT INTO P_NUTRIENT VALUES(SEQ_P_NUTRIENT_N_NO.NEXTVAL,SEQ_PIZZA_DOUGH_D_NO.CURRVAL,'L',
1205,'1조각',	151,	321	,17,	5,	462,	5
);
INSERT INTO P_NUTRIENT VALUES(SEQ_P_NUTRIENT_N_NO.NEXTVAL,SEQ_PIZZA_DOUGH_D_NO.CURRVAL,'M',
671,'2조각',	168,	366	,20	,6,	461,	5
);

INSERT INTO PIZZA_DOUGH VALUES(SEQ_PIZZA_DOUGH_D_NO.NEXTVAL,SEQ_PIZZA_P_NO.CURRVAL,2);
INSERT INTO P_NUTRIENT VALUES(SEQ_P_NUTRIENT_N_NO.NEXTVAL,SEQ_PIZZA_DOUGH_D_NO.CURRVAL,'L',
983,'1조각',	123,	246,	14	,5	,392,	4
);
INSERT INTO P_NUTRIENT VALUES(SEQ_P_NUTRIENT_N_NO.NEXTVAL,SEQ_PIZZA_DOUGH_D_NO.CURRVAL,'M',
555,'2조각',	139	,291,	16,	6,	494,	5
);

INSERT INTO PIZZA_DOUGH VALUES(SEQ_PIZZA_DOUGH_D_NO.NEXTVAL,SEQ_PIZZA_P_NO.CURRVAL,3);
INSERT INTO P_NUTRIENT VALUES(SEQ_P_NUTRIENT_N_NO.NEXTVAL,SEQ_PIZZA_DOUGH_D_NO.CURRVAL,'L',
889,'1조각',	111,	236,	13	,6	,353,	4
);
INSERT INTO P_NUTRIENT VALUES(SEQ_P_NUTRIENT_N_NO.NEXTVAL,SEQ_PIZZA_DOUGH_D_NO.CURRVAL,'M',
479,'2조각',	120,	251,	15	,7,	376,	5
);



INSERT INTO PIZZA_DOUGH VALUES(SEQ_PIZZA_DOUGH_D_NO.NEXTVAL,SEQ_PIZZA_P_NO.CURRVAL,4);
INSERT INTO P_NUTRIENT VALUES(SEQ_P_NUTRIENT_N_NO.NEXTVAL,SEQ_PIZZA_DOUGH_D_NO.CURRVAL,'L',
1170,'1조각',	146,	335	,15,	6	,579,	8
);
INSERT INTO P_NUTRIENT VALUES(SEQ_P_NUTRIENT_N_NO.NEXTVAL,SEQ_PIZZA_DOUGH_D_NO.CURRVAL,'M',
661,'2조각',	165,	385,	19,	6,	628,	9
);



INSERT INTO PIZZA VALUES(
SEQ_PIZZA_P_NO.NEXTVAL,
'슈퍼디럭스',
'클래식',
'모차렐라 치즈, 피망, 양파, 페퍼로니, 햄, 버섯, 불고기, 포크, 올리브',
18500,
24900,
'불고기(쇠고기): 호주산 / 포크 토핑(돼지고기): 국내산 / 햄(돼지고기): 국내산 / 모차렐라치즈: 미국산 / 페퍼로니: 돈육(국내산)+우육(호주산) / 오리지널, 나폴리 도우: 미국산, 캐나다산 / 씬 도우: 미국산',
'슈퍼디럭스.jpg',
'슈퍼디럭스H.png',
'슈퍼디럭스D.jpg',
'쇠고기, 페퍼로니, 햄, 버섯, 피망, 양파, 올리브 등 가장 많은 토핑이 들어가 풍부한 맛을 내는 피자!<br/>
무난한 맛으로 누구에게나 사랑받는 기본메뉴'
);
INSERT INTO PIZZA_DOUGH VALUES(SEQ_PIZZA_DOUGH_D_NO.NEXTVAL,SEQ_PIZZA_P_NO.CURRVAL,1);
INSERT INTO P_NUTRIENT VALUES(SEQ_P_NUTRIENT_N_NO.NEXTVAL,SEQ_PIZZA_DOUGH_D_NO.CURRVAL,'L',
1073,'1조각',	134,	307,	17,	5	,439,	3
);
INSERT INTO P_NUTRIENT VALUES(SEQ_P_NUTRIENT_N_NO.NEXTVAL,SEQ_PIZZA_DOUGH_D_NO.CURRVAL,'M',
599,'2조각',	150	,386,	19	,7	,481,	4
);


INSERT INTO PIZZA_DOUGH VALUES(SEQ_PIZZA_DOUGH_D_NO.NEXTVAL,SEQ_PIZZA_P_NO.CURRVAL,2);
INSERT INTO P_NUTRIENT VALUES(SEQ_P_NUTRIENT_N_NO.NEXTVAL,SEQ_PIZZA_DOUGH_D_NO.CURRVAL,'L',
856,'1조각',	107	,251,	12,	5	,358,	3
);
INSERT INTO P_NUTRIENT VALUES(SEQ_P_NUTRIENT_N_NO.NEXTVAL,SEQ_PIZZA_DOUGH_D_NO.CURRVAL,'M',
472,'2조각',	118	,282	,15	,6	,408	,3
);

INSERT INTO PIZZA_DOUGH VALUES(SEQ_PIZZA_DOUGH_D_NO.NEXTVAL,SEQ_PIZZA_P_NO.CURRVAL,3);
INSERT INTO P_NUTRIENT VALUES(SEQ_P_NUTRIENT_N_NO.NEXTVAL,SEQ_PIZZA_DOUGH_D_NO.CURRVAL,'L',
744,'2조각',	186,	450,	24,	12,	692,	4
);
INSERT INTO P_NUTRIENT VALUES(SEQ_P_NUTRIENT_N_NO.NEXTVAL,SEQ_PIZZA_DOUGH_D_NO.CURRVAL,'M',
414,'3조각',	155	,393,	20,	10,	542,	4
);

INSERT INTO PIZZA_DOUGH VALUES(SEQ_PIZZA_DOUGH_D_NO.NEXTVAL,SEQ_PIZZA_P_NO.CURRVAL,4);
INSERT INTO P_NUTRIENT VALUES(SEQ_P_NUTRIENT_N_NO.NEXTVAL,SEQ_PIZZA_DOUGH_D_NO.CURRVAL,'L',
1066,'1조각',	133,	332,	14,	5,	533,	3
);
INSERT INTO P_NUTRIENT VALUES(SEQ_P_NUTRIENT_N_NO.NEXTVAL,SEQ_PIZZA_DOUGH_D_NO.CURRVAL,'M',
595,'2조각',	149	,373,	16	,6,	629,	5
);



INSERT INTO PIZZA VALUES(
SEQ_PIZZA_P_NO.NEXTVAL,
'포테이토',
'클래식',
'모차렐라 치즈, 양파, 버섯, 옥수수, 감자, 베이컨, 마요네즈',
18500,
24900,
'베이컨(돼지고기): 미국산, 스페인산, 아일랜드산 / 모차렐라치즈: 미국산 / 오리지널, 나폴리 도우: 미국산, 캐나다산 / 씬 도우: 미국산',
'포테이토.jpg',
'포테이토H.png',
'포테이토D.jpg',
'고소한 감자, 베이컨, 버섯, 양파가 푸짐하게 어우러진 도미노피자의 인기메뉴<br/>
남녀노소 모두 좋아하는 담백한 웰빙피자'
);
INSERT INTO PIZZA_DOUGH VALUES(SEQ_PIZZA_DOUGH_D_NO.NEXTVAL,SEQ_PIZZA_P_NO.CURRVAL,1);
INSERT INTO P_NUTRIENT VALUES(SEQ_P_NUTRIENT_N_NO.NEXTVAL,SEQ_PIZZA_DOUGH_D_NO.CURRVAL,'L',
1110,'1조각',	139,	322	,15,	4	,380	,4
);
INSERT INTO P_NUTRIENT VALUES(SEQ_P_NUTRIENT_N_NO.NEXTVAL,SEQ_PIZZA_DOUGH_D_NO.CURRVAL,'M',
594,'2조각',	149	,352	,16	,5,	380,	4
);


INSERT INTO PIZZA_DOUGH VALUES(SEQ_PIZZA_DOUGH_D_NO.NEXTVAL,SEQ_PIZZA_P_NO.CURRVAL,2);
INSERT INTO P_NUTRIENT VALUES(SEQ_P_NUTRIENT_N_NO.NEXTVAL,SEQ_PIZZA_DOUGH_D_NO.CURRVAL,'L',
921,'1조각',	115,	260,	15,	4,	332	,3
);
INSERT INTO P_NUTRIENT VALUES(SEQ_P_NUTRIENT_N_NO.NEXTVAL,SEQ_PIZZA_DOUGH_D_NO.CURRVAL,'M',
486,'2조각',	122,	292,	16,	5,	338,	3
);

INSERT INTO PIZZA_DOUGH VALUES(SEQ_PIZZA_DOUGH_D_NO.NEXTVAL,SEQ_PIZZA_P_NO.CURRVAL,3);
INSERT INTO P_NUTRIENT VALUES(SEQ_P_NUTRIENT_N_NO.NEXTVAL,SEQ_PIZZA_DOUGH_D_NO.CURRVAL,'L',
820,'1조각',	103,	224,	12,	5,	298,	3
);
INSERT INTO P_NUTRIENT VALUES(SEQ_P_NUTRIENT_N_NO.NEXTVAL,SEQ_PIZZA_DOUGH_D_NO.CURRVAL,'M',
36,'2조각',	109,	243	,12	,5	,296	,3
);

INSERT INTO PIZZA_DOUGH VALUES(SEQ_PIZZA_DOUGH_D_NO.NEXTVAL,SEQ_PIZZA_P_NO.CURRVAL,4);
INSERT INTO P_NUTRIENT VALUES(SEQ_P_NUTRIENT_N_NO.NEXTVAL,SEQ_PIZZA_DOUGH_D_NO.CURRVAL,'L',
1113,'1조각',	139,	317,	15	,4	,349,	5
);
INSERT INTO P_NUTRIENT VALUES(SEQ_P_NUTRIENT_N_NO.NEXTVAL,SEQ_PIZZA_DOUGH_D_NO.CURRVAL,'M',
598,'2조각',	150,	350,	16	,4,	377,	5
);




INSERT INTO PIZZA VALUES(
SEQ_PIZZA_P_NO.NEXTVAL,
'리얼바비큐',
'클래식',
'리얼바비큐, 특제 바비큐 소스, 레드어니언, 모차렐라 치즈'||chr(38)||'체더치즈',
22500,
27900,
'리얼바비큐(쇠고기): 호주산 / 체더치즈: 뉴질랜드산 / 모차렐라치즈: 미국산 / 오리지널, 나폴리 도우: 미국산, 캐나다산 / 씬 도우: 미국산',
'리얼바비큐.jpg',
'리얼바비큐H.png',
'리얼바비큐D.jpg',
'숯불 특유의 그윽한 맛과 향이 배어있는 쇠고기와 레드어니언, 버섯, 파프리카 등 다양한 야채가 어우러져 캠핑바비큐의 맛을 피자로 즐길 수 있는 메뉴'
);


INSERT INTO PIZZA_DOUGH VALUES(SEQ_PIZZA_DOUGH_D_NO.NEXTVAL,SEQ_PIZZA_P_NO.CURRVAL,1);
INSERT INTO P_NUTRIENT VALUES(SEQ_P_NUTRIENT_N_NO.NEXTVAL,SEQ_PIZZA_DOUGH_D_NO.CURRVAL,'L',
977,'1조각',	122,	311,	17,	7,	509,	4
);
INSERT INTO P_NUTRIENT VALUES(SEQ_P_NUTRIENT_N_NO.NEXTVAL,SEQ_PIZZA_DOUGH_D_NO.CURRVAL,'M',
528,'2조각',	132,	354	,19,	8,	428,	7
);

INSERT INTO PIZZA_DOUGH VALUES(SEQ_PIZZA_DOUGH_D_NO.NEXTVAL,SEQ_PIZZA_P_NO.CURRVAL,2);
INSERT INTO P_NUTRIENT VALUES(SEQ_P_NUTRIENT_N_NO.NEXTVAL,SEQ_PIZZA_DOUGH_D_NO.CURRVAL,'L',
764,'2조각',	191,	499,	28,	12,	728,	7
);
INSERT INTO P_NUTRIENT VALUES(SEQ_P_NUTRIENT_N_NO.NEXTVAL,SEQ_PIZZA_DOUGH_D_NO.CURRVAL,'M',
418,'2조각',	105,	280	,17,	7,	400,	5
);


INSERT INTO PIZZA_DOUGH VALUES(SEQ_PIZZA_DOUGH_D_NO.NEXTVAL,SEQ_PIZZA_P_NO.CURRVAL,3);
INSERT INTO P_NUTRIENT VALUES(SEQ_P_NUTRIENT_N_NO.NEXTVAL,SEQ_PIZZA_DOUGH_D_NO.CURRVAL,'L',
627,'2조각',	157,	440	,22	,14	,627,	8
);
INSERT INTO P_NUTRIENT VALUES(SEQ_P_NUTRIENT_N_NO.NEXTVAL,SEQ_PIZZA_DOUGH_D_NO.CURRVAL,'M',
338,'3조각',	127,	287	,15,	8,	490	,5
);


INSERT INTO PIZZA_DOUGH VALUES(SEQ_PIZZA_DOUGH_D_NO.NEXTVAL,SEQ_PIZZA_P_NO.CURRVAL,4);
INSERT INTO P_NUTRIENT VALUES(SEQ_P_NUTRIENT_N_NO.NEXTVAL,SEQ_PIZZA_DOUGH_D_NO.CURRVAL,'L',
939,'1조각',	117,	317,	15,	6,	418,	5
);
INSERT INTO P_NUTRIENT VALUES(SEQ_P_NUTRIENT_N_NO.NEXTVAL,SEQ_PIZZA_DOUGH_D_NO.CURRVAL,'M',
537,'2조각',	134,	375,	17,	7,	482,	9
);


/*  사이드메뉴  */


INSERT INTO SIDE VALUES(SEQ_SIDE_S_NO.NEXTVAL,'화이트 크림 스파게티',8800,'화이트크림스파게티.jpg',
'베이컨칩(돼지고기): 미국산, 스페인산, 아일랜드산 *베이컨칩 일시적으로 와규크럼블로 대체 → 상세내용은 도미노뉴스를 확인 하시기 바랍니다.',
'베이컨과 크림소스가 어우러져 고소하면서 부드러운 맛을 즐길 수 있는 스파게티<br/>
*베이컨칩 일시적으로 와규크럼블로 대체 → 상세내용은 도미노뉴스를 확인 하시기 바랍니다.'
);

INSERT INTO S_NUTRIENT VALUES(SEQ_SIDE_S_NO.CURRVAL,
392,	851,	29,	29,	1258,	9
);



INSERT INTO SIDE VALUES(SEQ_SIDE_S_NO.NEXTVAL,'치즈 볼로네즈 스파게티',8800,'치즈볼로네즈스파게티.jpg',
'쇠고기: 호주산 / 모차렐라 치즈: 미국산',
'신선한 토마토만을 골라 만든 신선한 소스에 다진 쇠고기와 버섯까지 듬뿍!<br/>
자연의 깊은 맛과 치즈의 풍부한 맛이 어우러지는 정통 이탈리안 파스타!'
);

INSERT INTO S_NUTRIENT VALUES(SEQ_SIDE_S_NO.CURRVAL,
388	,524,	26,	11,	1117,	2
);


INSERT INTO SIDE VALUES(SEQ_SIDE_S_NO.NEXTVAL,'갈릭'||chr(38)||'허브윙스(8조각)','7800','갈릭'||chr(38)||'허브윙스(8조각).jpg',
'닭날개: 국내산',
'마늘과 허브로 하룻동안 숙성시켜 육질이 더욱 부드럽고 맛의 풍미가 더해진 닭날개를 케이준 씨즈닝으로 양념하여 오븐에 노릇노릇하게 구워낸 도미노만의 갈릭'||chr(38)||'허브 윙스.<br/>
기름에 튀기지 않아 더욱 깔끔합니다.'
);

INSERT INTO S_NUTRIENT VALUES(SEQ_SIDE_S_NO.CURRVAL,
315,	595,	47,	9,	964,	1
);


INSERT INTO SIDE VALUES(SEQ_SIDE_S_NO.NEXTVAL,'크리스피 치킨텐더(6조각)',7800,'크리스피치킨텐더(6조각).jpg',
'안심(닭고기): 국내산',
'닭고기의 가장 부드러운 부위인 안심을 후추, 마늘 등으로 시즈닝하여 튀긴 후 다시 오븐에서 구워내 겉은 바삭하면서 속은 부드러운 뼈 없는 치킨텐더'
);

INSERT INTO S_NUTRIENT VALUES(SEQ_SIDE_S_NO.CURRVAL,
300	,591	,45,	15,	588,	1
);


INSERT INTO SIDE VALUES(SEQ_SIDE_S_NO.NEXTVAL,'아란치니(한입리조또)',6200,'아란치니(한입리조또).jpg',
'쌀: 국내산',
'이탈리아에서 즐겨먹는 애피타이저로 리조또를 한 입에 먹을 수 있는 사이즈로 만들어 튀긴 메뉴 (10개)'
);

INSERT INTO S_NUTRIENT VALUES(SEQ_SIDE_S_NO.CURRVAL,
176,	530	,8	,3,	1195,	4
);


/*  할인쿠폰 */


INSERT INTO SAILE_COUPON VALUES(SEQ_SAILE_COUPON_C_NO.NEXTVAL,
'배달주문 20% 할인쿠폰','20',1
);

INSERT INTO SAILE_COUPON VALUES(SEQ_SAILE_COUPON_C_NO.NEXTVAL,
'배달주문 25% 할인쿠폰','25',1
);

INSERT INTO SAILE_COUPON VALUES(SEQ_SAILE_COUPON_C_NO.NEXTVAL,
'방문포장 35% 할인쿠폰','25',2
);
INSERT INTO SAILE_COUPON VALUES(SEQ_SAILE_COUPON_C_NO.NEXTVAL,
'방문포장 40% 할인쿠폰','40',2
);
INSERT INTO SAILE_COUPON VALUES(SEQ_SAILE_COUPON_C_NO.NEXTVAL,
'배달주문 30% 할인쿠폰','30',1
);
INSERT INTO SAILE_COUPON VALUES(SEQ_SAILE_COUPON_C_NO.NEXTVAL,
'생일방문포장 50% 할인쿠폰','50',2
);


/*   미나 - 커스터머   */


insert into customer values
('KIM','1234','김길동','M','19901212',
'153-759',
'서울특별시 금천구 가산디지털2로 123 월드메르디앙2차%&@#*^$@!4층 한국소프트웨어 인재개발원',
'bfhrbc12@naver.com',
'010-5555-4444');
insert into customer values
('HONG','1234','홍길순','W','19940321',
'100-861',
'서울특별시 중구 삼일대로6길 5 조양빌딩신관%&@#*^$@!서울충무로2가우체국',
'sdfiwet1278@nate.com',
'010-7777-4444');
insert into customer values
('LEE','1234','이길동','M','19580203',
'156-720',
'서울특별시 동작구 여의대방로16길 61%&@#*^$@!기상청청사',
'anonymous654@hanmail.net',
'010-5555-9999');
insert into customer values
('PARK','1234','박길순','W','19870512',
'121-807',
'서울특별시 마포구 서강로 144%&@#*^$@!KEB하나은행 신촌지점',
'lirjfg@naver.com',
'010-1111-3333');
insert into customer values
('CHOI','1234','최길순','W','19760828',
'121-837',
'서울특별시 마포구 와우산로23길 20-27 서교초등학교%&@#*^$@!2학년 3반',
'tbchdfg@gmail.com',
'010-9999-8888');
insert into customer values
('BACK','1234','백길동','M','19661110',
'151-848',
'서울특별시 관악구 남부순환로 1860 사랑의병원%&@#*^$@!202호',
'nydchedfg@gmail.com',
'010-2222-8888');


/* 회원등급 시험쿼리
RATING(등급) 테이블 */
INSERT INTO RATING VALUES(SEQ_RATING_R_NO.NEXTVAL, 'REGULAR', 0, 'REGULAR.png');
INSERT INTO CR_JOIN VALUES('LEE', SEQ_RATING_R_NO.CURRVAL, 'REGULAR' );
INSERT INTO CR_JOIN VALUES('BACK', SEQ_RATING_R_NO.CURRVAL, 'REGULAR' );
INSERT INTO CR_JOIN VALUES('PARK', SEQ_RATING_R_NO.CURRVAL, 'REGULAR' );
INSERT INTO RATING VALUES(SEQ_RATING_R_NO.NEXTVAL, 'PREMIUM', 2, 'PREMIUM.png');
INSERT INTO CR_JOIN VALUES('HONG', SEQ_RATING_R_NO.CURRVAL, 'PREMIUM' );
INSERT INTO CR_JOIN VALUES('KIM', SEQ_RATING_R_NO.CURRVAL, 'PREMIUM' );
INSERT INTO RATING VALUES(SEQ_RATING_R_NO.NEXTVAL, 'VIP', 6, 'VIP.png');
INSERT INTO CR_JOIN VALUES('CHOI', SEQ_RATING_R_NO.CURRVAL, 'VIP' );
/* ROYAL등급은 횟수 아닌 200만원임. */
INSERT INTO RATING VALUES(SEQ_RATING_R_NO.NEXTVAL, 'ROYAL', 2000000, 'ROYAL.png');

  /* 음료  */

INSERT INTO DRINK VALUES(SEQ_DRINK_DR_NO.NEXTVAL, '스프라이트 500ml', 1300, '스프라이트500ml.jpg');
INSERT INTO DRINK VALUES(SEQ_DRINK_DR_NO.NEXTVAL, '스프라이트 1.5L', 2100, '스프라이트1.5L.jpg');
INSERT INTO DRINK VALUES(SEQ_DRINK_DR_NO.NEXTVAL, '코카콜라 제로 500ml', 1300, '코카콜라제로 500ml.jpg');
INSERT INTO DRINK VALUES(SEQ_DRINK_DR_NO.NEXTVAL, '코카콜라 제로 1.5L', 2100, '코카콜라제로 1.5L.jpg');
INSERT INTO DRINK VALUES(SEQ_DRINK_DR_NO.NEXTVAL, '코카콜라 500ml', 1200, '코카콜라500ml.jpg');
INSERT INTO DRINK VALUES(SEQ_DRINK_DR_NO.NEXTVAL, '코카콜라 1.25L', 1800, '코카콜라1.25L.jpg');
INSERT INTO DRINK VALUES(SEQ_DRINK_DR_NO.NEXTVAL, '미닛메이드 스파클링 유자 350ml', 1200, '미닛메이드스파클링유자350ml.jpg');
INSERT INTO DRINK VALUES(SEQ_DRINK_DR_NO.NEXTVAL, '미닛메이드 스파클링 유자 1.25L', 2300, '미닛메이드스파클링유자1.25L.jpg');
INSERT INTO DRINK VALUES(SEQ_DRINK_DR_NO.NEXTVAL, '미닛메이드 스파클링 청포도 350ml', 1200, '미닛메이드스파클링청포도350ml.jpg');
INSERT INTO DRINK VALUES(SEQ_DRINK_DR_NO.NEXTVAL, '미닛메이드 스파클링 청포도 1.25L', 2300, '미닛메이드스파클링청포도1.25L.jpg');


  /*   소스 피클 */

INSERT INTO PICKLE VALUES(SEQ_PICKLE_PC_NO.NEXTVAL, '우리피클', 500, '우리피클.jpg');

INSERT INTO SAUCE VALUES(SEQ_SAUCE_SC_NO.NEXTVAL, '아몬드'||chr(38)||'호두 드레싱 (4가지 너츠)', 500, '아몬드'||chr(38)||'호두드레싱(4가지너츠).jpg');
INSERT INTO SAUCE VALUES(SEQ_SAUCE_SC_NO.NEXTVAL, '커리디핑소스', 500, '커리디핑소스.jpg');
INSERT INTO SAUCE VALUES(SEQ_SAUCE_SC_NO.NEXTVAL, '스위트 칠리소스 15g', 300, '스위트칠리소스15g.jpg');
INSERT INTO SAUCE VALUES(SEQ_SAUCE_SC_NO.NEXTVAL, '갈릭 디핑 소스 15g', 200, '갈릭디핑소스15g.jpg');
INSERT INTO SAUCE VALUES(SEQ_SAUCE_SC_NO.NEXTVAL, '핫소스', 100, '핫소스.jpg');


/*  피자_소스  */

INSERT INTO PIZZA_SAUCE VALUES(SEQ_PIZZA_SAUCE_PS_NO.NEXTVAL, '토마토소스');
INSERT INTO PIZZA_SAUCE VALUES(SEQ_PIZZA_SAUCE_PS_NO.NEXTVAL, '불고기소스');




/*   	TOPPING	TABLE	*/	




INSERT INTO TOPPING VALUES(		
SEQ_TOPPING_T_CODE.NEXTVAL,		
'양파',			
'양파.jpg',			
'메인',
NULL
);

INSERT INTO TOPPING_SIZE VALUES(
SEQ_TOPPING_SIZE_TS_NO.NEXTVAL,
SEQ_TOPPING_T_CODE.CURRVAL,
'S',
'300',
'20'
);

INSERT INTO TOPPING_SIZE VALUES(
SEQ_TOPPING_SIZE_TS_NO.NEXTVAL,
SEQ_TOPPING_T_CODE.CURRVAL,
'M',
'500',
'40'
);

INSERT INTO TOPPING_SIZE VALUES(
SEQ_TOPPING_SIZE_TS_NO.NEXTVAL,
SEQ_TOPPING_T_CODE.CURRVAL,
'L',
'1000',
'60'
);

INSERT INTO T_NUTRIENT VALUES(
SEQ_TOPPING_T_CODE.CURRVAL,
'25',
'0.8',
'0',
'7',
'3.99'
);




INSERT INTO TOPPING VALUES(		
SEQ_TOPPING_T_CODE.NEXTVAL,		
'피망',			
'피망.jpg',			
'메인',
NULL
);

INSERT INTO TOPPING_SIZE VALUES(
SEQ_TOPPING_SIZE_TS_NO.NEXTVAL,
SEQ_TOPPING_T_CODE.CURRVAL,
'S',
'300',
'20'
);

INSERT INTO TOPPING_SIZE VALUES(
SEQ_TOPPING_SIZE_TS_NO.NEXTVAL,
SEQ_TOPPING_T_CODE.CURRVAL,
'M',
'500',
'40'
);

INSERT INTO TOPPING_SIZE VALUES(
SEQ_TOPPING_SIZE_TS_NO.NEXTVAL,
SEQ_TOPPING_T_CODE.CURRVAL,
'L',
'1000',
'60'
);

INSERT INTO T_NUTRIENT VALUES(
SEQ_TOPPING_T_CODE.CURRVAL,
'20',
'0.8',
'0',
'7.5',
'1.92'
);





INSERT INTO TOPPING VALUES(		
SEQ_TOPPING_T_CODE.NEXTVAL,		
'버섯',			
'버섯.jpg',			
'메인',
NULL
);

INSERT INTO TOPPING_SIZE VALUES(
SEQ_TOPPING_SIZE_TS_NO.NEXTVAL,
SEQ_TOPPING_T_CODE.CURRVAL,
'S',
'300',
'20'
);

INSERT INTO TOPPING_SIZE VALUES(
SEQ_TOPPING_SIZE_TS_NO.NEXTVAL,
SEQ_TOPPING_T_CODE.CURRVAL,
'M',
'500',
'40'
);

INSERT INTO TOPPING_SIZE VALUES(
SEQ_TOPPING_SIZE_TS_NO.NEXTVAL,
SEQ_TOPPING_T_CODE.CURRVAL,
'L',
'1000',
'60'
);

INSERT INTO T_NUTRIENT VALUES(
SEQ_TOPPING_T_CODE.CURRVAL,
'30',
'1.1',
'0',
'2',
'0'
);




INSERT INTO TOPPING VALUES(		
SEQ_TOPPING_T_CODE.NEXTVAL,		
'옥수수',			
'옥수수.jpg',			
'메인',
NULL
);

INSERT INTO TOPPING_SIZE VALUES(
SEQ_TOPPING_SIZE_TS_NO.NEXTVAL,
SEQ_TOPPING_T_CODE.CURRVAL,
'S',
'300',
'40'
);

INSERT INTO TOPPING_SIZE VALUES(
SEQ_TOPPING_SIZE_TS_NO.NEXTVAL,
SEQ_TOPPING_T_CODE.CURRVAL,
'M',
'500',
'80'
);

INSERT INTO TOPPING_SIZE VALUES(
SEQ_TOPPING_SIZE_TS_NO.NEXTVAL,
SEQ_TOPPING_T_CODE.CURRVAL,
'L',
'1000',
'120'
);

INSERT INTO T_NUTRIENT VALUES(
SEQ_TOPPING_T_CODE.CURRVAL,
'100',
'3',
'0',
'180',
'6'
);



INSERT INTO TOPPING VALUES(		
SEQ_TOPPING_T_CODE.NEXTVAL,		
'올리브',			
'올리브.jpg',			
'메인',
NULL
);

INSERT INTO TOPPING_SIZE VALUES(
SEQ_TOPPING_SIZE_TS_NO.NEXTVAL,
SEQ_TOPPING_T_CODE.CURRVAL,
'S',
'300',
'20'
);

INSERT INTO TOPPING_SIZE VALUES(
SEQ_TOPPING_SIZE_TS_NO.NEXTVAL,
SEQ_TOPPING_T_CODE.CURRVAL,
'M',
'500',
'40'
);

INSERT INTO TOPPING_SIZE VALUES(
SEQ_TOPPING_SIZE_TS_NO.NEXTVAL,
SEQ_TOPPING_T_CODE.CURRVAL,
'L',
'1000',
'60'
);

INSERT INTO T_NUTRIENT VALUES(
SEQ_TOPPING_T_CODE.CURRVAL,
'130',
'0.5',
'2.3',
'0.7',
'0'
);




INSERT INTO TOPPING VALUES(		
SEQ_TOPPING_T_CODE.NEXTVAL,		
'베이컨',			
'베이컨.jpg',			
'메인',
'돼지고기'
);

INSERT INTO TOPPING_SIZE VALUES(
SEQ_TOPPING_SIZE_TS_NO.NEXTVAL,
SEQ_TOPPING_T_CODE.CURRVAL,
'S',
'500',
'18'
);

INSERT INTO TOPPING_SIZE VALUES(
SEQ_TOPPING_SIZE_TS_NO.NEXTVAL,
SEQ_TOPPING_T_CODE.CURRVAL,
'M',
'1000',
'24'
);

INSERT INTO TOPPING_SIZE VALUES(
SEQ_TOPPING_SIZE_TS_NO.NEXTVAL,
SEQ_TOPPING_T_CODE.CURRVAL,
'L',
'2000',
'48'
);

INSERT INTO T_NUTRIENT VALUES(
SEQ_TOPPING_T_CODE.CURRVAL,
'287',
'17',
'7',
'680',
'0'
);


INSERT INTO TOPPING VALUES(		
SEQ_TOPPING_T_CODE.NEXTVAL,		
'케이준새우살',			
'케이준새우살.jpg',			
'메인',
NULL
);

INSERT INTO TOPPING_SIZE VALUES(
SEQ_TOPPING_SIZE_TS_NO.NEXTVAL,
SEQ_TOPPING_T_CODE.CURRVAL,
'S',
'2000',
'45'
);

INSERT INTO TOPPING_SIZE VALUES(
SEQ_TOPPING_SIZE_TS_NO.NEXTVAL,
SEQ_TOPPING_T_CODE.CURRVAL,
'M',
'4000',
'64'
);

INSERT INTO TOPPING_SIZE VALUES(
SEQ_TOPPING_SIZE_TS_NO.NEXTVAL,
SEQ_TOPPING_T_CODE.CURRVAL,
'L',
'6000',
'124'
);

INSERT INTO T_NUTRIENT VALUES(
SEQ_TOPPING_T_CODE.CURRVAL,
'59',
'14.2',
'0.1',
'595',
'0'
);












INSERT INTO TOPPING VALUES(		
SEQ_TOPPING_T_CODE.NEXTVAL,		
'직화 스테이크',			
'직화스테이크.jpg',			
'메인',
'쇠고기, 대두, 밀'
);

INSERT INTO TOPPING_SIZE VALUES(
SEQ_TOPPING_SIZE_TS_NO.NEXTVAL,
SEQ_TOPPING_T_CODE.CURRVAL,
'S',
'3000',
'30'
);

INSERT INTO TOPPING_SIZE VALUES(
SEQ_TOPPING_SIZE_TS_NO.NEXTVAL,
SEQ_TOPPING_T_CODE.CURRVAL,
'M',
'4000',
'45'
);

INSERT INTO TOPPING_SIZE VALUES(
SEQ_TOPPING_SIZE_TS_NO.NEXTVAL,
SEQ_TOPPING_T_CODE.CURRVAL,
'L',
'5000',
'60'
);



INSERT INTO TOPPING VALUES(
SEQ_TOPPING_T_CODE.NEXTVAL,
'비스테카 스테이크',
'비스테카스테이크.jpg',
'메인',
'쇠고기, 밀, 대두, 토마토'
);

INSERT INTO TOPPING_SIZE VALUES(
SEQ_TOPPING_SIZE_TS_NO.NEXTVAL,
SEQ_TOPPING_T_CODE.CURRVAL,
'S',
'3000',
'30'
);

INSERT INTO TOPPING_SIZE VALUES(
SEQ_TOPPING_SIZE_TS_NO.NEXTVAL,
SEQ_TOPPING_T_CODE.CURRVAL,
'M',
'4000',
'40'
);

INSERT INTO TOPPING_SIZE VALUES(
SEQ_TOPPING_SIZE_TS_NO.NEXTVAL,
SEQ_TOPPING_T_CODE.CURRVAL,
'L',
'5000',
'50'
);



 
INSERT INTO TOPPING VALUES(
SEQ_TOPPING_T_CODE.NEXTVAL,
'브레이즈드 포크',
'브레이즈드포크.jpg',
'메인',
'돼지고기, 대두, 토마토'
);

INSERT INTO TOPPING_SIZE VALUES(
SEQ_TOPPING_SIZE_TS_NO.NEXTVAL,
SEQ_TOPPING_T_CODE.CURRVAL,
'S',
'1000',
'20'
);

INSERT INTO TOPPING_SIZE VALUES(
SEQ_TOPPING_SIZE_TS_NO.NEXTVAL,
SEQ_TOPPING_T_CODE.CURRVAL,
'M',
'1500',
'30'
);

INSERT INTO TOPPING_SIZE VALUES(
SEQ_TOPPING_SIZE_TS_NO.NEXTVAL,
SEQ_TOPPING_T_CODE.CURRVAL,
'L',
'2000',
'40'
);




INSERT INTO TOPPING VALUES(		
SEQ_TOPPING_T_CODE.NEXTVAL,	
'프로볼로네 치즈',
'프로볼로네치즈.jpg',
'치즈',
'우유'
);

INSERT INTO TOPPING_SIZE VALUES(
SEQ_TOPPING_SIZE_TS_NO.NEXTVAL,
SEQ_TOPPING_T_CODE.CURRVAL,
'S',
'2000',
'40'
);

INSERT INTO TOPPING_SIZE VALUES(
SEQ_TOPPING_SIZE_TS_NO.NEXTVAL,
SEQ_TOPPING_T_CODE.CURRVAL,
'M',
'3000',
'60'
);

INSERT INTO TOPPING_SIZE VALUES(
SEQ_TOPPING_SIZE_TS_NO.NEXTVAL,
SEQ_TOPPING_T_CODE.CURRVAL,
'L',
'4000',
'80'
);




INSERT INTO TOPPING VALUES(
SEQ_TOPPING_T_CODE.NEXTVAL,
'도미노치즈',
'도미노치즈.jpg',
'치즈',
'우유'
);
INSERT INTO TOPPING_SIZE VALUES(
SEQ_TOPPING_SIZE_TS_NO.NEXTVAL,
SEQ_TOPPING_T_CODE.CURRVAL,
'S',
'2500',
'100'
);

INSERT INTO TOPPING_SIZE VALUES(
SEQ_TOPPING_SIZE_TS_NO.NEXTVAL,
SEQ_TOPPING_T_CODE.CURRVAL,
'M',
'4000',
'120'
);

INSERT INTO TOPPING_SIZE VALUES(
SEQ_TOPPING_SIZE_TS_NO.NEXTVAL,
SEQ_TOPPING_T_CODE.CURRVAL,
'L',
'5500',
'140'
);




INSERT INTO TOPPING VALUES(
SEQ_TOPPING_T_CODE.NEXTVAL,
'파르메산 치즈',
'파르메산치즈.jpg',
'애프터',
'우유'
);

INSERT INTO TOPPING_SIZE VALUES(
SEQ_TOPPING_SIZE_TS_NO.NEXTVAL,
SEQ_TOPPING_T_CODE.CURRVAL,
'S',
'1000',
'5'
);

INSERT INTO TOPPING_SIZE VALUES(
SEQ_TOPPING_SIZE_TS_NO.NEXTVAL,
SEQ_TOPPING_T_CODE.CURRVAL,
'M',
'2000',
'10'
);

INSERT INTO TOPPING_SIZE VALUES(
SEQ_TOPPING_SIZE_TS_NO.NEXTVAL,
SEQ_TOPPING_T_CODE.CURRVAL,
'L',
'3000',
'15'
);





INSERT INTO TOPPING VALUES(
SEQ_TOPPING_T_CODE.NEXTVAL,
'만체고 치즈',
'만체고치즈.jpg',
'애프터',
'우유'
);

INSERT INTO TOPPING_SIZE VALUES(
SEQ_TOPPING_SIZE_TS_NO.NEXTVAL,
SEQ_TOPPING_T_CODE.CURRVAL,
'S',
'1000',
'20'
);

INSERT INTO TOPPING_SIZE VALUES(
SEQ_TOPPING_SIZE_TS_NO.NEXTVAL,
SEQ_TOPPING_T_CODE.CURRVAL,
'M',
'2000',
'40'
);

INSERT INTO TOPPING_SIZE VALUES(
SEQ_TOPPING_SIZE_TS_NO.NEXTVAL,
SEQ_TOPPING_T_CODE.CURRVAL,
'L',
'3000',
'60'
);



INSERT INTO TOPPING VALUES(
SEQ_TOPPING_T_CODE.NEXTVAL,
'호스래디시소스',
'호스래디시소스.jpg',
'애프터',
'계란, 우유, 대두'
);

INSERT INTO TOPPING_SIZE VALUES(
SEQ_TOPPING_SIZE_TS_NO.NEXTVAL,
SEQ_TOPPING_T_CODE.CURRVAL,
'S',
'1000',
'30'
);

INSERT INTO TOPPING_SIZE VALUES(
SEQ_TOPPING_SIZE_TS_NO.NEXTVAL,
SEQ_TOPPING_T_CODE.CURRVAL,
'M',
'2000',
'50'
);

INSERT INTO TOPPING_SIZE VALUES(
SEQ_TOPPING_SIZE_TS_NO.NEXTVAL,
SEQ_TOPPING_T_CODE.CURRVAL,
'L',
'3000',
'70'
);







/*  스토어  */


INSERT INTO STORES VALUES(SEQ_STORES_ST_NO.NEXTVAL,
'도미노피자 도봉점',
'dominodb','pizza',
'02-1577-3082',
'132-819','서울 도봉구 도봉로 775 %&@#*^$@! 도미노피자 도봉점',
'주차 가능',
'12:00-02:00',
37.6737091, 127.04398519999995,
'도봉역 5분거리'
);


INSERT INTO SALES VALUES(SEQ_SALES_SA_NO.NEXTVAL, 'KIM', SEQ_STORES_ST_NO.CURRVAL, '서울특별시 금천구 가산디지털2로 123 월드메르디앙2차%&@#*^$@!4층 한국소프트웨어 인재개발원', SYSDATE, '주문 상태 - 승인'
,'김길동','010-5555-4444','없음',1
);
INSERT INTO SALES_MENU VALUES(SEQ_SALES_MENU_SM_NO.NEXTVAL, SEQ_SALES_SA_NO.CURRVAL, 29, 1, '치즈', 1, 'L', 21200);
INSERT INTO PIZZARANK VALUES(7,SEQ_SALES_SA_NO.CURRVAL,SYSDATE);

INSERT INTO S_TOPPING VALUES(
SEQ_SALES_MENU_SM_NO.CURRVAL,
4
);




INSERT INTO SALES_MENU VALUES(SEQ_SALES_MENU_SM_NO.NEXTVAL, SEQ_SALES_SA_NO.CURRVAL, 3, 5, '스위트 칠리소스 15g', 2, NULL, 300);

INSERT INTO SALES_MENU VALUES(SEQ_SALES_MENU_SM_NO.NEXTVAL, SEQ_SALES_SA_NO.CURRVAL, 1, 4, '우리피클', 1, NULL, 500);


INSERT INTO SALES_PRICE VALUES(
SEQ_SALES_SA_NO.CURRVAL,22000,0,0,22000);



INSERT INTO STORES VALUES(SEQ_STORES_ST_NO.NEXTVAL,
'가산점',
'dominogs','pizza',
'010-1234-5678',
'153-801','서울특별시 금천구 가산로 146 %&@#*^$@! 도미노피자 가산점',
'주차 불가',
'12:00-02:00',
37.4783093, 126.89102460000004,
'가산디지털단지역 5분거리'
);

INSERT INTO SALES VALUES(SEQ_SALES_SA_NO.NEXTVAL, 'PARK',SEQ_STORES_ST_NO.CURRVAL, '서울특별시 마포구 서강로 144%&@#*^$@!KEB하나은행 신촌지점', SYSDATE, '주문 상태 - 미승인'
,'박길동','010-5555-4444','없음',2
);
INSERT INTO SALES_MENU VALUES(SEQ_SALES_MENU_SM_NO.NEXTVAL, SEQ_SALES_SA_NO.CURRVAL, 10, 1, '베이컨체더치즈', 13, 'L', 24900);
INSERT INTO PIZZARANK VALUES(10,SEQ_SALES_SA_NO.CURRVAL,SYSDATE);
INSERT INTO SALES_MENU VALUES(SEQ_SALES_MENU_SM_NO.NEXTVAL, SEQ_SALES_SA_NO.CURRVAL, 1, 4, '우리피클', 1, NULL, 500);
INSERT INTO SALES_MENU VALUES(SEQ_SALES_MENU_SM_NO.NEXTVAL, SEQ_SALES_SA_NO.CURRVAL, 2, 5, '커리디핑소스', 1, NULL, 500);


INSERT INTO SALES_PRICE VALUES(
SEQ_SALES_SA_NO.CURRVAL,25900,0,0,25900);


INSERT INTO STORES VALUES(SEQ_STORES_ST_NO.NEXTVAL,
'논현점',
'dominonh','pizza',
'010-4321-1234',
'135-822','서울특별시 강남구 학동로4길 15 %&@#*^$@! 동화상가 도미노피자 논현점',
'주차 불가',
'12:00-02:00',
37.5036391, 127.02591610000002,
'논현초등학교 5분거리'
);


INSERT INTO SALES VALUES(SEQ_SALES_SA_NO.NEXTVAL, 'LEE', SEQ_STORES_ST_NO.CURRVAL, '서울특별시 동작구 여의대방로16길 61%&@#*^$@!기상청청사', SYSDATE, '주문 상태 - 승인');
INSERT INTO SALES_MENU VALUES(SEQ_SALES_MENU_SM_NO.NEXTVAL, SEQ_SALES_SA_NO.CURRVAL, 45, 1, '슈퍼슈프림', 2, 'L', 24900);

INSERT INTO SALES_PRICE VALUES(
SEQ_SALES_SA_NO.CURRVAL,24900,0,0,24900);


INSERT INTO STORES VALUES(SEQ_STORES_ST_NO.NEXTVAL,
'구로점',
'dominogr','pizza',
'010-9876-5432',
'152-858','서울 구로구 구로동로 218 %&@#*^$@! 도피노피자 구로점',
'주차 불가',
'12:00-02:00',
37.4979773, 126.88270999999997,
'구로역 5분거리'
);


INSERT INTO SALES VALUES(SEQ_SALES_SA_NO.NEXTVAL, 'BACK', SEQ_STORES_ST_NO.CURRVAL, '서울특별시 관악구 남부순환로 1860 사랑의병원%&@#*^$@!202호', SYSDATE, '주문 상태 - 미승인'
,'백길동','010-5555-4444','없음',3
);
INSERT INTO SALES_MENU VALUES(SEQ_SALES_MENU_SM_NO.NEXTVAL, SEQ_SALES_SA_NO.CURRVAL, 37, 1, '불고기', 1, 'L', 24700);
INSERT INTO PIZZARANK VALUES(9,SEQ_SALES_SA_NO.CURRVAL,SYSDATE);
INSERT INTO PIZZARANK VALUES(9,SEQ_SALES_SA_NO.CURRVAL,SYSDATE);


INSERT INTO S_TOPPING VALUES(
SEQ_SALES_MENU_SM_NO.CURRVAL,
2
);
INSERT INTO S_TOPPING VALUES(
SEQ_SALES_MENU_SM_NO.CURRVAL,
4
);


INSERT INTO SALES_MENU VALUES(SEQ_SALES_MENU_SM_NO.NEXTVAL, SEQ_SALES_SA_NO.CURRVAL, 1, 4, '우리피클', 1, NULL, 500);
INSERT INTO SALES_MENU VALUES(SEQ_SALES_MENU_SM_NO.NEXTVAL, SEQ_SALES_SA_NO.CURRVAL, 2, 5, '커리디핑소스', 1, NULL, 500);
INSERT INTO SALES_MENU VALUES(SEQ_SALES_MENU_SM_NO.NEXTVAL, SEQ_SALES_SA_NO.CURRVAL, 4, 5, '갈릭 디핑 소스 15g', 1, NULL, 200);


INSERT INTO SALES_PRICE VALUES(
SEQ_SALES_SA_NO.CURRVAL,25900,0,0,25900);


INSERT INTO STORES VALUES(SEQ_STORES_ST_NO.NEXTVAL,
'대림점',
'dominodr','pizza',
'010-5678-6543',
'150-820','서울 영등포구 신길로 39 %&@#*^$@! 썬프라자 도미노피자 대림점',
'주차 가능',
'10:00-24:00',
37.4961476, 126.90789819999998,
'대림역 5분거리'
);
INSERT INTO SALES VALUES(SEQ_SALES_SA_NO.NEXTVAL, 'CHOI', SEQ_STORES_ST_NO.CURRVAL, '서울특별시 마포구 와우산로23길 20-27 서교초등학교%&@#*^$@!2학년 3반', SYSDATE, '주문 상태 - 미승인'
,'최길동','010-5555-4444','없음',4
);
INSERT INTO SALES_MENU VALUES(SEQ_SALES_MENU_SM_NO.NEXTVAL, SEQ_SALES_SA_NO.CURRVAL, 50, 1, '슈퍼디럭스', 2, 'L', 24900);
INSERT INTO PIZZARANK VALUES(12,SEQ_SALES_SA_NO.CURRVAL,SYSDATE);

INSERT INTO SALES_PRICE VALUES(
SEQ_SALES_SA_NO.CURRVAL,24900,0,0,24900);


INSERT INTO STORES VALUES(SEQ_STORES_ST_NO.NEXTVAL,
 '명동점',
 'myeongdong',
'myeongdong1234',
 '02-2264-3089',
 '100-846',
 '서울특별시 중구 마른내로 47 (초동)',
 '매장주차불가',
 '11:00 ~ 22:00',
37.5646969,126.99317329999997,
'*'
);

INSERT INTO SALES VALUES(SEQ_SALES_SA_NO.NEXTVAL, 'HONG', SEQ_STORES_ST_NO.CURRVAL, '서울특별시 중구 삼일대로6길 5 조양빌딩신관%&@#*^$@!서울충무로2가우체국', SYSDATE, '주문 상태 - 승인'
,'홍길동','010-5555-4444','없음',1
);
INSERT INTO SALES_MENU VALUES(SEQ_SALES_MENU_SM_NO.NEXTVAL, SEQ_SALES_SA_NO.CURRVAL, 55, 1, '포테이토', 1, 'L', 25700);
INSERT INTO PIZZARANK VALUES(13,SEQ_SALES_SA_NO.CURRVAL,SYSDATE);
INSERT INTO PIZZARANK VALUES(6,SEQ_SALES_SA_NO.CURRVAL,SYSDATE);
INSERT INTO PIZZARANK VALUES(5,SEQ_SALES_SA_NO.CURRVAL,SYSDATE);
INSERT INTO PIZZARANK VALUES(4,SEQ_SALES_SA_NO.CURRVAL,SYSDATE);
INSERT INTO PIZZARANK VALUES(12,SEQ_SALES_SA_NO.CURRVAL,SYSDATE);
INSERT INTO PIZZARANK VALUES(3,SEQ_SALES_SA_NO.CURRVAL,SYSDATE);
INSERT INTO PIZZARANK VALUES(11,SEQ_SALES_SA_NO.CURRVAL,SYSDATE);


INSERT INTO S_TOPPING VALUES(
SEQ_SALES_MENU_SM_NO.CURRVAL,
1
);
INSERT INTO S_TOPPING VALUES(
SEQ_SALES_MENU_SM_NO.CURRVAL,
2
);


INSERT INTO SALES_MENU VALUES(SEQ_SALES_MENU_SM_NO.NEXTVAL, SEQ_SALES_SA_NO.CURRVAL, 1, 4, '우리피클', 1, NULL, 500);

INSERT INTO SALES_PRICE VALUES(
SEQ_SALES_SA_NO.CURRVAL,26200,0,0,26200);




/*  게시판 */


INSERT INTO NOTICE VALUES(
SEQ_NOTICE_N_NO.NEXTVAL,
'5월 매니아 변경사항 사전공지 안내',
'안녕하세요 도미노피자 입니다.
항상 변함없이 저희 도미노피자를 이용해 주셔서 감사합니다.
<br/>
많은 고객 분의 요청에 의해 아래와 같이 Royal 등급을 5월 2일부로 재운영 할 예정입니다.
앞으로도 고객님의 소중한 의견에 귀기울이고 반영할 수 있는 도미노피자가 되겠습니다.
<br/>
감사합니다.',
'2017-04-26',
'5월매니아_Img',
'1',
'546'
);

INSERT INTO NOTICE VALUES(
SEQ_NOTICE_N_NO.NEXTVAL,
'[공지] 삼성카드 포인트카드 제휴 일시중단 안내',
'안녕하세요. 도미노피자 입니다.
<br/> 
4/1(토)부터 삼성카드 보너스포인트 100% 사용으로 변경될 예정이었으나 
카드사와 결제시스템사간 전산이슈로 포인트 사용 제휴서비스가 당분간 중단됩니다.
<br/>  
이용에 불편을 드려 죄송하며, 빠른 시일 내 이용에 불편함이 없도록 최선을 다하겠습니다.
감사합니다.',
'2017-03-31',
'삼성중단_Img',
'1',
'2456'
);

INSERT INTO NOTICE VALUES(
SEQ_NOTICE_N_NO.NEXTVAL,
'[공지] 도미노피자 겨울 신제품 출시 사진행사 취재 안내',
'[공지] 도미노피자 겨울 신제품 출시 사진행사 취재 안내
도미노피자가 새롭게 선보이는 겨울 신제품 사진행사를 아래와 같이 실시하오니
취재일정에 참고하시기 바랍니다.
<br/>
- 아래 -
<br/>
일시 : 2016년 11월 15일(화) 오전 10~11시
장소 : 세종문화회관 예술동 1층 예인홀(광화문역 1번 출구 앞)
대상 : 각 언론사 사진부 기자님
내용 : 도미노피자 겨울 신제품 출시 기념 사진행사
<br/> 
<br/> 
※문의 : 02-3270-7924 / lk16565@prbank.co.kr',
'2016-11-14',
'',
'2',
'158'
);


INSERT INTO NOTICE VALUES(
SEQ_NOTICE_N_NO.NEXTVAL,
'송중기.박보검이 함께한 크리스마스 한정판 패키지 출시',
'세계 최대 피자배달 전문 기업 도미노피자(www.dominos.co.kr, 대표 오광현)는 연말 시즌을 맞아 송중기´박보검 두 남자가 함께 성탄절 분위기를 연출하는 크리스마스 한정판 패키지를 오는 12월 23일 선보인다고 밝혔다.
<br/>  
이번 크리스마스 패키지는 내년 1월 1일까지 모든 피자 구매 시 선착순 제공되며 산타 모자, 니트 등을 착용한 송중기´박보검의 이미지와 해피 홀리데이(Happy holiday) 문구로 연말 감성을 더한다.
<br/>  
도미노피자 관계자는 “사랑하는 사람들과 함께 뜻깊은 시간을 보내는 연말, 고객들에게 도미노피자만의 색다른 선물을 선사하기 위해 이번 크리스마스 패키지를 선보였다”며 “연말 모임에서 남녀노소 누구나 즐겨 찾는 도미노피자를 통해 모두가 함께 행복한 시간을 보내시기 바란다”고 말했다. ',
'2016-12-14',
'패키지_Img',
'2',
'392'
);

INSERT INTO NOTICE VALUES(
SEQ_NOTICE_N_NO.NEXTVAL,
'봄 신제품 시식 체험단 모집',
'세계 최대 피자배달 전문 기업 도미노피자(www.dominos.co.kr, 대표 오광현)는 공식 출시에 앞서 신제품을 미리 맛볼 수 있는 ‘봄 신제품 시식 체험단’을 모집한다고 2일 밝혔다.
<br/> 
이번 ‘봄 신제품 시식 체험단’은 오늘(2일)부터 6일까지 5일 동안 도미노피자 공식 SNS 채널을 통해 총 340명을 모집한다.
<br/> 
도미노피자의 신제품 시식을 원하는 고객이라면 누구나 응모 가능하며 도미노피자 공식 블로그, 페이스북, 인스타그램, 트위터, 카카오스토리 등에서 참여 희망 댓글을 남기면 된다. 추첨을 통해 선정된 체험단에게는 봄 신제품 시식과 평가의 기회를 무료로 제공한다.
<br/> 
도미노피자 관계자는 “2017년 첫 신제품 출시를 앞두고 고객들과 함께 도미노피자만의 품평회를 열고자 이번 시식 체험단을 운영하게 됐다”라며 “봄의 시작을 알리는 신제품을 미리 맛볼 수 있는 기회인 만큼 도미노피자를 사랑해주시는 고객 여러분의 많은 참여를 부탁드린다”고 전했다. <끝>',
'2016-10-04',
'시식_Img',
'2',
'506'
);


/* 이벤트 */

INSERT INTO EVENT VALUES(
SEQ_EVENT_E_NO.NEXTVAL,
'Mega Week! 어메이징한 피자 40% 할인이 돌아왔다~',
'2017-09-04',
'2017-09-10',
'Mega_TImg',
'Mega_CImg'
);

INSERT INTO EVENT VALUES(
SEQ_EVENT_E_NO.NEXTVAL,
'KT 고객이라면 누구나 누릴 수 있는 특별한 더블할인 혜택!',
'2017-09-01',
'2017-12-31',
'KT_TImg',
'KT_CImg'
);

INSERT INTO EVENT VALUES(
SEQ_EVENT_E_NO.NEXTVAL,
'혼자서 간편하게 먹을 수 있는 NEW 싱글피자 3종 출시!',
'2017-08-25',
'2017-09-21',
'싱글_TImg',
'싱글_CImg'
);

INSERT INTO EVENT VALUES(
SEQ_EVENT_E_NO.NEXTVAL,
'가을맞이 풍성한 맛의 향연! 신제품 사이드디시 3종 출시',
'2017-08-25',
'2017-09-21',
'Side_TImg',
'Side_CImg'
);

INSERT INTO EVENT VALUES(
SEQ_EVENT_E_NO.NEXTVAL,
'현대카드ZERO/M Edition2 신규발급시 피자할인쿠폰 증정!',
'2017-09-01',
'2017-09-30',
'현대_TImg',
'현대_CImg'
);


INSERT INTO ADMIN_TAB VALUES(
'domino','pizza');


/*KIM 쿠폰 부여*/

insert into my_cupon values(
SEQ_MY_CUPON_MC_NO.NEXTVAL,'KIM',SYSDATE,SYSDATE,2);

insert into my_cupon values(
SEQ_MY_CUPON_MC_NO.NEXTVAL,'KIM',SYSDATE,SYSDATE,3);

insert into my_cupon values(
SEQ_MY_CUPON_MC_NO.NEXTVAL,'KIM',SYSDATE,SYSDATE,4);











/*

//기프티콘 
INSERT INTO GIFTCONE VALUES('123456-654321'
*/














/*
 바꾼거
P_NUTRIENT - 1회 기준 수량, 중량 추가

SAILE_COUPON - 사용 조건(배달,방문포장,생일,모두)

 

customer, rating, cr_join, sales, sales_menu, PIZZA-CLASSIC,
TOPPING, DRINK, PICKLE, SAUCE
*/





